import type { ResearchDossier } from '../types'

/* Standard-tier bundled dossiers: full financial history, valuation and memo;
   framework lenses scored with one-line verdicts (no per-question detail).
   All figures approximate, labeled sample data. */

export const MSFT_DOSSIER: ResearchDossier = {
  symbol: 'MSFT',
  tier: 'standard',
  dataProfile: { provider: 'bundled-sample', asOf: '2026-07-18', note: 'Approximate historicals through FY2025 (Jun). USD billions.' },
  profile: {
    name: 'Microsoft Corp.',
    description: 'Enterprise software and cloud platform monetizing productivity (M365), infrastructure (Azure) and AI (Copilot) across the world’s businesses.',
    sector: 'Technology', industry: 'Software & cloud platforms', country: 'US', currency: 'USD', unit: 'USD billions', benchmark: 'SPY',
    marketNarrative: 'The safest AI play: Azure + Copilot attach converts the AI wave into recurring revenue with minimal disruption risk.',
    segments: [
      { name: 'Intelligent Cloud (Azure)', revenuePct: 43 },
      { name: 'Productivity (M365, LinkedIn)', revenuePct: 32 },
      { name: 'More Personal Computing', revenuePct: 25 },
    ],
    geographies: [ { name: 'US', revenuePct: 51 }, { name: 'International', revenuePct: 49 } ],
    moat: { rating: 'wide', direction: 'stable', basis: 'Enterprise switching costs, distribution via existing agreements, identity/security stickiness (Entra), scale economics in cloud.' },
    risks: [
      { label: 'AI capex payback', detail: '$80B+/yr capex assumes AI revenue materializes at software margins; depreciation will pressure margins first.', underappreciated: true },
      { label: 'OpenAI relationship complexity', detail: 'Partner, investor, competitor and landlord simultaneously.' },
      { label: 'Regulatory', detail: 'Bundling scrutiny (Teams) and cloud-licensing complaints in the EU.' },
    ],
    management: { assessment: 'Transformed capital allocation and culture since 2014; disciplined M&A record post-LinkedIn.', capitalAllocation: 'R&D + capex first; consistent dividend growth; buybacks offset dilution and shrink modestly.' },
    accountingFlags: [ { label: 'Server useful-life extensions', severity: 'low', detail: 'Depreciation schedule changes flattered margins in FY23–24 — disclosed, worth normalizing.' } ],
  },
  financials: [
    { fy: 'FY2018', revenue: 110.4, grossMarginPct: 65.2, ebitMarginPct: 31.8, netIncome: 30.3, eps: 3.88, fcf: 32.3, shares: 7.7, roicPct: 22, netDebt: -55, dividendsPerShare: 1.68 },
    { fy: 'FY2019', revenue: 125.8, grossMarginPct: 65.9, ebitMarginPct: 34.1, netIncome: 39.2, eps: 5.06, fcf: 38.3, shares: 7.7, roicPct: 26, netDebt: -60, dividendsPerShare: 1.84 },
    { fy: 'FY2020', revenue: 143.0, grossMarginPct: 67.8, ebitMarginPct: 37.0, netIncome: 44.3, eps: 5.76, fcf: 45.2, shares: 7.6, roicPct: 28, netDebt: -70, dividendsPerShare: 2.04 },
    { fy: 'FY2021', revenue: 168.1, grossMarginPct: 68.9, ebitMarginPct: 41.6, netIncome: 61.3, eps: 8.05, fcf: 56.1, shares: 7.5, roicPct: 33, netDebt: -75, dividendsPerShare: 2.24 },
    { fy: 'FY2022', revenue: 198.3, grossMarginPct: 68.4, ebitMarginPct: 42.0, netIncome: 72.7, eps: 9.65, fcf: 65.1, shares: 7.5, roicPct: 35, netDebt: -60, dividendsPerShare: 2.48 },
    { fy: 'FY2023', revenue: 211.9, grossMarginPct: 68.9, ebitMarginPct: 41.8, netIncome: 72.4, eps: 9.68, fcf: 59.5, shares: 7.4, roicPct: 32, netDebt: -40, dividendsPerShare: 2.72 },
    { fy: 'FY2024', revenue: 245.1, grossMarginPct: 69.8, ebitMarginPct: 44.6, netIncome: 88.1, eps: 11.8, fcf: 74.1, shares: 7.4, roicPct: 33, netDebt: -20, dividendsPerShare: 3.0 },
    { fy: 'FY2025e', revenue: 279.0, grossMarginPct: 69.5, ebitMarginPct: 45.0, netIncome: 101.0, eps: 13.6, fcf: 72.0, shares: 7.4, roicPct: 32, netDebt: 5, dividendsPerShare: 3.32 },
  ],
  estimateRevisions: [ { period: 'FY2026 Azure growth', direction: 'up', note: 'Consensus nudged to ~30% cc on AI services contribution.' } ],
  valuation: {
    methodNotes: 'DCF appropriate (highly predictable FCF) but must model the capex supercycle explicitly — FCF is temporarily depressed relative to earnings. EV/EBITDA misleads during a depreciation ramp; P/E and DCF preferred.',
    dcf: { fcf0: 72, growthY1_5: 14, growthY6_10: 9, terminalGrowth: 3.5, discountRate: 9, netCash: -5, shares: 7.4 },
    scenarios: [
      { label: 'Bull', narrative: 'Copilot attach >20% of eligible seats; Azure holds ~30% growth; capex peaks FY2027.', eps5: 24, exitMultiple: 32, probabilityPct: 30 },
      { label: 'Base', narrative: 'Azure mid-20s growth; AI margin drag through FY2027, then leverage.', eps5: 21, exitMultiple: 27, probabilityPct: 50 },
      { label: 'Bear', narrative: 'AI monetization disappoints; depreciation bites; growth decelerates to mid-teens.', eps5: 17, exitMultiple: 21, probabilityPct: 20 },
    ],
    historicalMultiples: [
      { label: 'P/E (NTM)', low: 18, median: 28, high: 37, current: 33 },
      { label: 'FCF yield %', low: 1.8, median: 3.2, high: 5.5, current: 2.1 },
    ],
    peers: [
      { symbol: 'GOOGL', name: 'Alphabet', multiple: 23, metric: 'P/E NTM' },
      { symbol: 'AMZN', name: 'Amazon', multiple: 34, metric: 'P/E NTM' },
      { symbol: 'ORCL', name: 'Oracle', multiple: 28, metric: 'P/E NTM' },
    ],
  },
  frameworks: [
    { id: 'buffett', score: 8, verdict: 'Wide moat, rational allocation, predictable demand — price full but not silly for the quality.' },
    { id: 'lynch', score: 6.5, verdict: 'Stalwart with a growth kicker; PEG ~2.3 — pay-up territory.' },
    { id: 'graham', score: 3.5, verdict: 'No discount, no asset case — outside the lens.' },
    { id: 'fisher', score: 8.5, verdict: 'R&D-to-product engine plus best-in-class enterprise salesforce.' },
    { id: 'marks', score: 5, verdict: 'Consensus darling; the risk is everyone agreeing, not the business.' },
    { id: 'greenblatt', score: 5.5, verdict: 'Good ROC, modest earnings yield (~3%).' },
    { id: 'smith', score: 8.5, verdict: 'Canonical Fundsmith holding profile: high sustained ROCE, organic reinvestment.' },
    { id: 'damodaran', score: 6, verdict: 'Price implies ~13–14% FCF growth post-capex normalization — demanding, defensible.' },
    { id: 'druckenmiller', score: 6, verdict: 'AI monetization is a slow-burn inflection; liquidity supportive.' },
    { id: 'mauboussin', score: 6.5, verdict: 'Long CAP justified by switching costs; expectations near the edge of base rates.' },
    { id: 'chanos', score: 7.5, verdict: 'Clean, though watch useful-life extensions and AI capex capitalization.' },
  ],
  memo: {
    oneLiner: 'The most durable large-cap compounder — currently spending a fortune to stay that way.',
    narrative: 'Safest AI beneficiary; Azure + Copilot compound recurring revenue.',
    variantPerception: 'Capex depreciation will bite margins before AI revenue proves out — a 2027 air pocket the market glosses over. Long-term thesis unaffected; entry points may improve.',
    bull: 'Copilot attach inflects; EPS $24 by FY2030 at premium multiple.',
    base: '~13% EPS CAGR; multiple drifts to 27× → ~10%/yr total return.',
    bear: 'AI ROI questioned; margin compression; 21× on $17 → flat-to-down stock.',
    assumptions: ['Azure grows ≥25% through FY2028', 'AI capex peaks FY2027', 'Copilot ARPU accretive by FY2028', 'No structural regulatory remedy'],
    reasonsToOwn: ['Deepest enterprise moat in software', 'AI monetized through existing contracts', 'Fortress balance sheet'],
    reasonsNotToOwn: ['33× NTM with FCF temporarily depressed', 'Capex payback unproven', 'Crowded consensus long'],
    catalysts: [ { date: '2026-07-28', label: 'Q4 FY26 earnings + FY27 capex guide', kind: 'earnings' } ],
    thesisBreakers: ['Azure growth <20% for two quarters', 'Capex guided up again without AI revenue proof'],
    leadingIndicators: ['Azure cc growth', 'Copilot seat disclosures', 'Capex/depreciation guidance'],
    valuationRange: { low: 330, high: 560 },
    expectedReturnPct: { y1: 5, y3: 16, y5: 29 },
    status: 'Hold',
    statusRationale: 'Core holding at full price. The FY2027 depreciation air pocket is the most likely add-point; hold and be ready.',
  },
  news: [
    { date: '2026-07-08', title: 'Copilot enterprise seats disclosed above 15M', source: { label: 'Company blog (sample)', date: '2026-07-08', kind: 'sample_data' }, materiality: 'material', why: 'First hard datapoint for the attach assumption.', affectsAssumption: 'Copilot ARPU accretive by FY2028' },
    { date: '2026-06-15', title: 'EU accepts Teams unbundling commitments', source: { label: 'Regulatory notice (sample)', date: '2026-06-15', kind: 'sample_data' }, materiality: 'relevant', why: 'Removes a modest regulatory overhang.' },
  ],
  qualityScores: [
    { key: 'managementCapital', label: 'Management & capital allocation', score: 9, basis: 'Decade of value-creating reinvestment; disciplined M&A.' },
    { key: 'moat', label: 'Competitive advantage', score: 9, basis: 'Widest enterprise moat in software.' },
  ],
  snapshots: [ { date: '2026-05-02', status: 'Hold', note: 'Initiated: core compounder, full price.' } ],
}

export const COST_DOSSIER: ResearchDossier = {
  symbol: 'COST',
  tier: 'standard',
  dataProfile: { provider: 'bundled-sample', asOf: '2026-07-18', note: 'Approximate historicals through FY2025 (Aug); FY2025 estimated. USD billions.' },
  profile: {
    name: 'Costco Wholesale',
    description: 'Membership warehouse club selling curated goods at near-cost, earning its profit from membership fees rather than merchandise.',
    sector: 'Consumer Staples', industry: 'Warehouse retail', country: 'US', currency: 'USD', unit: 'USD billions', benchmark: 'SPY',
    marketNarrative: 'The highest-quality retailer alive: renewal rates >90%, untouched by e-commerce, with decades of international runway.',
    segments: [ { name: 'Merchandise', revenuePct: 98, note: '~11% gross margin by design' }, { name: 'Membership fees', revenuePct: 2, note: '≈ 70% of operating profit' } ],
    geographies: [ { name: 'US & Canada', revenuePct: 86 }, { name: 'International', revenuePct: 14, note: 'The growth runway' } ],
    moat: { rating: 'wide', direction: 'stable', basis: 'Scale-enabled price leadership + membership psychology + treasure-hunt merchandising; the model is well understood yet unreplicated.' },
    risks: [
      { label: 'Valuation', detail: 'A 52× P/E for an 8% grower is the risk. The business has almost none.', underappreciated: false },
      { label: 'Succession cadence', detail: 'Culture is the moat’s engine; leadership transitions are the only structural threat.' },
    ],
    management: { assessment: 'Legendarily conservative; pricing discipline enforced culturally.', capitalAllocation: 'Steady stores + special dividends; no buyback aggression, no empire building.' },
    accountingFlags: [ { label: 'Pristine', severity: 'low', detail: 'Membership deferral straightforward; inventory turns faster than payables — negative working capital.' } ],
  },
  financials: [
    { fy: 'FY2018', revenue: 141.6, grossMarginPct: 13.0, ebitMarginPct: 3.2, netIncome: 3.13, eps: 7.09, fcf: 2.8, shares: 0.44, roicPct: 17, netDebt: -1.0, dividendsPerShare: 2.14 },
    { fy: 'FY2019', revenue: 152.7, grossMarginPct: 13.0, ebitMarginPct: 3.2, netIncome: 3.66, eps: 8.26, fcf: 3.4, shares: 0.44, roicPct: 19, netDebt: -2.0, dividendsPerShare: 2.44 },
    { fy: 'FY2020', revenue: 166.8, grossMarginPct: 13.1, ebitMarginPct: 3.3, netIncome: 4.0, eps: 9.02, fcf: 6.1, shares: 0.44, roicPct: 20, netDebt: -5.0, dividendsPerShare: 2.7 },
    { fy: 'FY2021', revenue: 195.9, grossMarginPct: 13.1, ebitMarginPct: 3.4, netIncome: 5.0, eps: 11.27, fcf: 5.4, shares: 0.44, roicPct: 22, netDebt: -6.0, dividendsPerShare: 2.98 },
    { fy: 'FY2022', revenue: 227.0, grossMarginPct: 12.1, ebitMarginPct: 3.4, netIncome: 5.84, eps: 13.14, fcf: 3.5, shares: 0.44, roicPct: 24, netDebt: -4.0, dividendsPerShare: 3.38 },
    { fy: 'FY2023', revenue: 242.3, grossMarginPct: 12.6, ebitMarginPct: 3.4, netIncome: 6.29, eps: 14.16, fcf: 6.7, shares: 0.44, roicPct: 25, netDebt: -8.0, dividendsPerShare: 3.84 },
    { fy: 'FY2024', revenue: 254.5, grossMarginPct: 12.9, ebitMarginPct: 3.7, netIncome: 7.37, eps: 16.56, fcf: 6.6, shares: 0.44, roicPct: 27, netDebt: -9.0, dividendsPerShare: 4.16 },
    { fy: 'FY2025e', revenue: 275.0, grossMarginPct: 13.0, ebitMarginPct: 3.8, netIncome: 8.1, eps: 18.2, fcf: 7.4, shares: 0.44, roicPct: 28, netDebt: -10.0, dividendsPerShare: 4.64 },
  ],
  estimateRevisions: [ { period: 'FY2026 comps', direction: 'flat', note: 'Steady ~6% comp assumptions; fee increase cycle due FY2027.' } ],
  valuation: {
    methodNotes: 'Earnings-based methods fit (fee income = annuity). The entire debate is the multiple: the business justifies a premium; 52× prices in perfection plus scarcity value. DCF included; a membership-annuity SOTP is a useful cross-check.',
    dcf: { fcf0: 7.4, growthY1_5: 9, growthY6_10: 7, terminalGrowth: 3.5, discountRate: 8.5, netCash: 10, shares: 0.44 },
    scenarios: [
      { label: 'Bull', narrative: 'International acceleration + fee increase; multiple holds.', eps5: 27, exitMultiple: 45, probabilityPct: 25 },
      { label: 'Base', narrative: '8% EPS compounding; multiple drifts toward 38×.', eps5: 26, exitMultiple: 38, probabilityPct: 55 },
      { label: 'Bear', narrative: 'Multiple mean-reverts to 30× on rate/valuation rotation; business fine.', eps5: 24, exitMultiple: 30, probabilityPct: 20 },
    ],
    historicalMultiples: [ { label: 'P/E (NTM)', low: 25, median: 36, high: 55, current: 52 }, { label: 'FCF yield %', low: 1.2, median: 2.4, high: 4.0, current: 1.9 } ],
    peers: [ { symbol: 'WMT', name: 'Walmart', multiple: 34, metric: 'P/E NTM' }, { symbol: 'BJ', name: "BJ's Wholesale", multiple: 24, metric: 'P/E NTM' } ],
  },
  frameworks: [
    { id: 'buffett', score: 8.5, verdict: 'A Munger favorite for cause: moat, integrity, customer devotion — price is the only quarrel.' },
    { id: 'lynch', score: 5.5, verdict: 'Stalwart at a fast-grower price; PEG ~5 fails the test outright.' },
    { id: 'graham', score: 2.5, verdict: 'Nothing quantitative here for Graham.' },
    { id: 'fisher', score: 7.5, verdict: 'Organization quality and repeatable expansion formula score highly.' },
    { id: 'marks', score: 4, verdict: 'Beloved by everyone — scarcity-premium psychology is the position’s biggest content.' },
    { id: 'greenblatt', score: 4, verdict: '~2% earnings yield; formula walks away.' },
    { id: 'smith', score: 7, verdict: 'Quality passes with distinction; "do not overpay" clearly violated.' },
    { id: 'damodaran', score: 4.5, verdict: 'Price implies ~14% FCF growth for a business guiding 8% — narrative and numbers disagree.' },
    { id: 'druckenmiller', score: 3.5, verdict: 'No inflection, no asymmetry — nothing to size.' },
    { id: 'mauboussin', score: 5, verdict: 'Expectations exceed retail base rates by a wide margin; CAP assumption heroic.' },
    { id: 'chanos', score: 9, verdict: 'As clean as public-company accounting gets.' },
  ],
  memo: {
    oneLiner: 'A perfect business at an imperfect price.',
    narrative: 'Compounding certainty deserves any multiple — the "quality bubble" thesis in one stock.',
    variantPerception: 'Nothing is wrong except the price; a passive de-rating to 38× costs three years of returns. Patience is a position.',
    bull: 'Fee hike + international + multiple holds → low-teens IRR.',
    base: 'EPS compounds 8–9%; multiple drifts down → ~4–6% IRR.',
    bear: 'De-rating to 30× → flat five years despite perfect execution.',
    assumptions: ['Renewal rates >90%', 'Membership fee increase FY2027', '25–30 net new warehouses/yr'],
    reasonsToOwn: ['Most defensible retail model extant', 'Fee annuity + negative working capital', 'Culture-driven pricing moat'],
    reasonsNotToOwn: ['52× for 8% growth', 'Return profile dominated by multiple risk', 'Better entry prices likely within a normal cycle'],
    catalysts: [ { date: '2026-09-24', label: 'Q4 FY26 earnings + fee-hike commentary', kind: 'earnings' } ],
    thesisBreakers: ['Renewal rate <88%', 'Comp deceleration below 4% sustained'],
    leadingIndicators: ['Monthly comps', 'Renewal rate', 'Executive membership penetration'],
    valuationRange: { low: 720, high: 1150 },
    expectedReturnPct: { y1: 1, y3: 6, y5: 11 },
    status: 'Hold',
    statusRationale: 'Own it, don’t add. Set the add-alert at ≤38× forward (~$700) where the quality is free.',
  },
  news: [ { date: '2026-05-29', title: 'May comps +6.4%; e-commerce +19%', source: { label: 'Monthly sales release (sample)', date: '2026-05-29', kind: 'sample_data' }, materiality: 'relevant', why: 'Confirms steady-state assumptions.' } ],
  qualityScores: [
    { key: 'managementCapital', label: 'Management & capital allocation', score: 9, basis: 'Special-dividend discipline; no ego capital.' },
    { key: 'moat', label: 'Competitive advantage', score: 9, basis: 'Scale economies shared with the customer — structurally unassailable.' },
  ],
  snapshots: [ { date: '2026-05-02', status: 'Hold', note: 'Initiated: quality 10, price 3.' } ],
}

export const TCS_DOSSIER: ResearchDossier = {
  symbol: 'TCS',
  tier: 'standard',
  dataProfile: { provider: 'bundled-sample', asOf: '2026-07-11', note: 'Approximate historicals through FY2025 (Mar). INR billions.' },
  profile: {
    name: 'Tata Consultancy Services',
    description: 'The world’s largest IT-services firm by profit, converting Indian engineering scale into multi-decade enterprise relationships.',
    sector: 'Technology', industry: 'IT services', country: 'IN', currency: 'INR', unit: 'INR billions', benchmark: 'NIFTY50',
    marketNarrative: 'A dividend-paying compounder whose AI narrative cuts both ways: productivity boon or seat-based-pricing threat.',
    segments: [ { name: 'BFSI', revenuePct: 32 }, { name: 'Retail & CPG', revenuePct: 16 }, { name: 'Communications & Media', revenuePct: 10 }, { name: 'Manufacturing', revenuePct: 12 }, { name: 'Life Sciences & other', revenuePct: 30 } ],
    geographies: [ { name: 'North America', revenuePct: 50 }, { name: 'UK & Europe', revenuePct: 31 }, { name: 'India + RoW', revenuePct: 19 } ],
    moat: { rating: 'narrow', direction: 'weakening', basis: 'Relationship depth + delivery scale + Tata brand. GenAI-driven pricing compression is a genuine secular question for the whole industry.' },
    risks: [
      { label: 'GenAI deflation', detail: 'If AI collapses effort-based pricing faster than TCS captures AI project work, revenue per employee inverts.', underappreciated: false },
      { label: 'US immigration/visa policy', detail: 'Perennial cost and delivery-model overhang.' },
      { label: 'Client concentration in BFSI', detail: 'A US/EU banking downturn hits bookings with a lag.' },
    ],
    management: { assessment: 'Institutional depth; conservative, dividend-first culture.', capitalAllocation: '~85%+ payout via dividends/buybacks; zero-debt fortress.' },
    accountingFlags: [ { label: 'Clean', severity: 'low', detail: 'Cash conversion consistently ~100% of net income; unbilled revenue stable.' } ],
  },
  financials: [
    { fy: 'FY2018', revenue: 1231, grossMarginPct: 41, ebitMarginPct: 24.7, netIncome: 258, eps: 67, fcf: 235, shares: 3.83, roicPct: 35, netDebt: -450, dividendsPerShare: 29 },
    { fy: 'FY2019', revenue: 1464, grossMarginPct: 41, ebitMarginPct: 25.6, netIncome: 315, eps: 83, fcf: 285, shares: 3.79, roicPct: 38, netDebt: -480, dividendsPerShare: 34 },
    { fy: 'FY2020', revenue: 1569, grossMarginPct: 41, ebitMarginPct: 24.6, netIncome: 323, eps: 86, fcf: 310, shares: 3.75, roicPct: 37, netDebt: -420, dividendsPerShare: 73 },
    { fy: 'FY2021', revenue: 1642, grossMarginPct: 42, ebitMarginPct: 25.9, netIncome: 324, eps: 87, fcf: 380, shares: 3.7, roicPct: 38, netDebt: -500, dividendsPerShare: 38 },
    { fy: 'FY2022', revenue: 1917, grossMarginPct: 41, ebitMarginPct: 25.3, netIncome: 383, eps: 104, fcf: 355, shares: 3.66, roicPct: 42, netDebt: -520, dividendsPerShare: 43 },
    { fy: 'FY2023', revenue: 2255, grossMarginPct: 40, ebitMarginPct: 24.1, netIncome: 421, eps: 115, fcf: 390, shares: 3.66, roicPct: 44, netDebt: -480, dividendsPerShare: 115 },
    { fy: 'FY2024', revenue: 2408, grossMarginPct: 40, ebitMarginPct: 24.6, netIncome: 459, eps: 127, fcf: 425, shares: 3.62, roicPct: 46, netDebt: -500, dividendsPerShare: 73 },
    { fy: 'FY2025', revenue: 2553, grossMarginPct: 40, ebitMarginPct: 24.3, netIncome: 485, eps: 134, fcf: 450, shares: 3.62, roicPct: 46, netDebt: -530, dividendsPerShare: 126 },
  ],
  estimateRevisions: [ { period: 'FY2027 revenue', direction: 'down', note: 'Consensus trimmed ~1% on discretionary-spend softness; AI deal wins offsetting slowly.' } ],
  valuation: {
    methodNotes: 'A dividend-discount / FCF-yield business: near-total payout, minimal reinvestment need. P/E vs its own band and DDM are primary; growth-based methods secondary because reinvestment is intentionally small.',
    dcf: { fcf0: 450, growthY1_5: 8, growthY6_10: 6, terminalGrowth: 4, discountRate: 11.5, netCash: 530, shares: 3.62 },
    scenarios: [
      { label: 'Bull', narrative: 'AI services wave nets positive; margin to 26%+.', eps5: 205, exitMultiple: 27, probabilityPct: 20 },
      { label: 'Base', narrative: 'HSD revenue growth; margins stable; payout continues.', eps5: 190, exitMultiple: 24, probabilityPct: 55 },
      { label: 'Bear', narrative: 'GenAI pricing deflation outruns volume; growth stalls to LSD.', eps5: 155, exitMultiple: 18, probabilityPct: 25 },
    ],
    historicalMultiples: [ { label: 'P/E (NTM)', low: 18, median: 26, high: 35, current: 28 }, { label: 'Dividend yield %', low: 1.1, median: 1.9, high: 3.2, current: 3.1 } ],
    peers: [ { symbol: 'INFY', name: 'Infosys', multiple: 24, metric: 'P/E NTM' }, { symbol: 'ACN', name: 'Accenture', multiple: 26, metric: 'P/E NTM' } ],
  },
  frameworks: [
    { id: 'buffett', score: 7, verdict: 'High-ROIC, shareholder-friendly, understandable — with a genuine question over moat durability under AI.' },
    { id: 'lynch', score: 5.5, verdict: 'Slow grower now; own it for yield, not for the story.' },
    { id: 'graham', score: 6.5, verdict: 'Net cash, stable earnings, 3.1% yield — the closest thing to a Graham stock in this book.' },
    { id: 'fisher', score: 5, verdict: 'Sales org world-class; product innovation not the model.' },
    { id: 'marks', score: 6.5, verdict: 'Pessimism (AI kills IT services) is at least half priced — decent second-level setup if deflation proves gradual.' },
    { id: 'greenblatt', score: 7, verdict: 'High ROC with a ~4.5% earnings yield — screens respectably.' },
    { id: 'smith', score: 6.5, verdict: 'High sustained ROCE, but reinvestment runway (Smith’s engine) is deliberately absent.' },
    { id: 'damodaran', score: 6.5, verdict: 'Price implies ~6% growth — undemanding; the narrative risk is the tail, not the base.' },
    { id: 'druckenmiller', score: 3, verdict: 'No inflection; negative revisions. Nothing to size.' },
    { id: 'mauboussin', score: 6, verdict: 'Expectations below service-sector base rates — a rare margin of expectations safety.' },
    { id: 'chanos', score: 8.5, verdict: 'Forensically pristine; cash conversion near 100% for a decade.' },
  ],
  memo: {
    oneLiner: 'A bond-plus-optionality: 3% yield, fortress balance sheet, and a coin-flip on what AI does to IT services.',
    narrative: 'AI threatens effort-based pricing; the sector de-rates until proven otherwise.',
    variantPerception: 'Deflation will be slower than feared and TCS captures disproportionate AI-migration work through incumbency — while being paid 3% to wait.',
    bull: 'AI net-positive; re-rate to 27× on ₹205 EPS.',
    base: 'HSD compounding + dividends → ~11% INR IRR (≈9% USD after currency drag).',
    bear: 'Pricing deflation; 18× on ₹155 → negative real returns.',
    assumptions: ['GenAI pricing impact <2%/yr net of volume', 'BFSI spend recovers FY2027', 'Payout ratio ≥85% sustained'],
    reasonsToOwn: ['Highest-quality balance sheet in the book', 'Paid to wait via dividends', 'Incumbency advantage in AI migrations'],
    reasonsNotToOwn: ['Secular AI question unresolved', 'Growth structurally slower than history', 'INR drag for USD goals'],
    catalysts: [ { date: '2026-10-09', label: 'Q2 FY27 results + deal-win (TCV) disclosure', kind: 'earnings' } ],
    thesisBreakers: ['TCV declining YoY for 3 quarters', 'Revenue per employee down >5% without margin offset'],
    leadingIndicators: ['TCV bookings', 'Revenue per employee', 'BFSI vertical growth', 'Attrition'],
    valuationRange: { low: 2900, high: 5200 },
    expectedReturnPct: { y1: 6, y3: 13, y5: 21 },
    status: 'Hold',
    statusRationale: 'Yield floor + cheap expectations balance the AI tail risk. Hold within the India sleeve; revisit on TCV trend.',
  },
  news: [ { date: '2026-07-09', title: 'Q1 FY27: revenue +6.2% cc; TCV $11.2B', source: { label: 'Earnings release (sample)', date: '2026-07-09', kind: 'sample_data' }, materiality: 'relevant', why: 'Bookings stable — deflation thesis not accelerating.' } ],
  qualityScores: [
    { key: 'managementCapital', label: 'Management & capital allocation', score: 8, basis: 'Near-total payout, zero-debt discipline.' },
    { key: 'moat', label: 'Competitive advantage', score: 6, basis: 'Narrow and, honestly, weakening at the industry level.' },
  ],
  snapshots: [ { date: '2026-05-04', status: 'Hold', note: 'Initiated: yield + expectations safety vs AI tail.' } ],
}

export const O_DOSSIER: ResearchDossier = {
  symbol: 'O',
  tier: 'standard',
  dataProfile: { provider: 'bundled-sample', asOf: '2026-07-18', note: 'Approximate historicals through FY2025. USD billions; per-share figures are AFFO-based where noted.' },
  profile: {
    name: 'Realty Income Corp.',
    description: 'A net-lease REIT collecting monthly rent from ~15,500 single-tenant retail and industrial properties on long triple-net leases.',
    sector: 'Real Estate', industry: 'Net-lease REIT', country: 'US', currency: 'USD', unit: 'USD billions', benchmark: 'SPY',
    marketNarrative: 'A bond proxy: monthly dividends at 5.4% yield, hostage to interest rates.',
    segments: [ { name: 'Retail net lease', revenuePct: 79, note: 'Convenience, dollar stores, drug, grocery' }, { name: 'Industrial & other', revenuePct: 15 }, { name: 'Gaming & data centers', revenuePct: 6, note: 'Newer verticals' } ],
    geographies: [ { name: 'US', revenuePct: 89 }, { name: 'UK & Europe', revenuePct: 11 } ],
    moat: { rating: 'narrow', direction: 'stable', basis: 'Cost of capital advantage + scale in sale-leaseback origination. The moat is the balance sheet, which is rate-dependent.' },
    risks: [
      { label: 'Rate sensitivity', detail: 'AFFO spread compresses when refinancing above in-place cap rates.' },
      { label: 'Tenant credit', detail: 'Dollar stores and drug retail under structural pressure (~15% of rent).', underappreciated: true },
      { label: 'External growth model', detail: 'Growth requires perpetual equity issuance at accretive prices — reflexive to the share price itself.' },
    ],
    management: { assessment: 'Disciplined underwriting record across cycles; 30 years of monthly dividends, 25+ years of increases.', capitalAllocation: 'Spread investing: issue equity/debt, buy at wider cap rates; accretion math is transparent.' },
    accountingFlags: [ { label: 'AFFO adjustments', severity: 'low', detail: 'Standard REIT adjustments; straight-line rent and amortization handled conventionally.' } ],
  },
  financials: [
    { fy: 'FY2018', revenue: 1.33, ebitMarginPct: 48, netIncome: 0.36, eps: 3.12, fcf: 0.92, shares: 0.3, netDebt: 6.5, dividendsPerShare: 2.63 },
    { fy: 'FY2019', revenue: 1.49, ebitMarginPct: 49, netIncome: 0.44, eps: 3.29, fcf: 1.06, shares: 0.32, netDebt: 7.9, dividendsPerShare: 2.71 },
    { fy: 'FY2020', revenue: 1.65, ebitMarginPct: 47, netIncome: 0.4, eps: 3.39, fcf: 1.17, shares: 0.35, netDebt: 8.8, dividendsPerShare: 2.79 },
    { fy: 'FY2021', revenue: 2.08, ebitMarginPct: 46, netIncome: 0.36, eps: 3.59, fcf: 1.45, shares: 0.4, netDebt: 12.5, dividendsPerShare: 2.83 },
    { fy: 'FY2022', revenue: 3.34, ebitMarginPct: 47, netIncome: 0.87, eps: 3.92, fcf: 2.4, shares: 0.61, netDebt: 17.5, dividendsPerShare: 2.97 },
    { fy: 'FY2023', revenue: 4.08, ebitMarginPct: 47, netIncome: 0.87, eps: 4.0, fcf: 2.9, shares: 0.69, netDebt: 21.5, dividendsPerShare: 3.05 },
    { fy: 'FY2024', revenue: 5.27, ebitMarginPct: 47, netIncome: 0.86, eps: 4.19, fcf: 3.6, shares: 0.87, netDebt: 26.5, dividendsPerShare: 3.13 },
    { fy: 'FY2025e', revenue: 5.55, ebitMarginPct: 47, netIncome: 0.95, eps: 4.32, fcf: 3.8, shares: 0.9, netDebt: 27.0, dividendsPerShare: 3.21 },
  ],
  estimateRevisions: [ { period: 'FY2026 AFFO/share', direction: 'flat', note: 'Guide ~$4.40; acquisition volume rate-dependent.' } ],
  valuation: {
    methodNotes: 'EPS shown is AFFO per share — the correct earnings measure for net-lease REITs (GAAP EPS is depreciation-distorted). Valuation via P/AFFO vs history, dividend-discount, and spread-to-treasury. DCF on corporate FCF is NOT meaningful for an externally-funded REIT.',
    dcf: { fcf0: 3.8, growthY1_5: 4, growthY6_10: 3, terminalGrowth: 2, discountRate: 8, netCash: -27, shares: 0.9 },
    scenarios: [
      { label: 'Bull', narrative: 'Rates fall 150bp; P/AFFO re-rates to 16×; spread investing reaccelerates.', eps5: 5.1, exitMultiple: 16, probabilityPct: 25 },
      { label: 'Base', narrative: 'Rates rangebound; 4%/yr AFFO growth; 13.5× multiple.', eps5: 5.0, exitMultiple: 13.5, probabilityPct: 55 },
      { label: 'Bear', narrative: 'Tenant credit losses (drug/dollar) + higher-for-longer; 11× on $4.60.', eps5: 4.6, exitMultiple: 11, probabilityPct: 20 },
    ],
    historicalMultiples: [ { label: 'P/AFFO', low: 11, median: 16, high: 22, current: 13.6 }, { label: 'Dividend yield %', low: 3.5, median: 4.4, high: 6.3, current: 5.4 } ],
    peers: [ { symbol: 'NNN', name: 'NNN REIT', multiple: 12.5, metric: 'P/AFFO' }, { symbol: 'WPC', name: 'W. P. Carey', multiple: 12, metric: 'P/AFFO' } ],
  },
  frameworks: [
    { id: 'buffett', score: 5.5, verdict: 'Understandable and honestly run, but returns are spread-dependent, not moat-dependent.' },
    { id: 'lynch', score: 6, verdict: 'Classic slow grower — own for the dividend, judge by payout safety. On that test it passes.' },
    { id: 'graham', score: 7, verdict: 'Real assets, 30-year dividend record, below-median multiple — a Graham-respectable income security.' },
    { id: 'fisher', score: 3, verdict: 'Not a Fisher business; innovation not the model.', applicability: 'Lens inapplicable; excluded from weighting by default.' },
    { id: 'marks', score: 6.5, verdict: 'Rate pessimism is the position; you are paid 5.4% for consensus to stay wrong slowly.' },
    { id: 'greenblatt', score: 3.5, verdict: 'Formula not designed for REITs — leverage and depreciation distort both inputs.', applicability: 'Structurally inapplicable.' },
    { id: 'smith', score: 3, verdict: 'External-equity growth model is the opposite of the Fundsmith engine.', applicability: 'Structurally inapplicable.' },
    { id: 'damodaran', score: 6.5, verdict: 'Price implies ~2% AFFO growth — below the delivered record; modest expectations gap in your favor.' },
    { id: 'druckenmiller', score: 5, verdict: 'A rates trade wearing a REIT costume; asymmetric only if you hold a rate view.' },
    { id: 'mauboussin', score: 5.5, verdict: 'Expectations below base rates for this platform; CAP question is really a cost-of-capital question.' },
    { id: 'chanos', score: 7.5, verdict: 'Transparent AFFO bridge; watch tenant credit (dollar/drug) concentrations, not accounting.' },
  ],
  memo: {
    oneLiner: 'A 5.4% monthly coupon with modest growth — owned for income, threatened mainly by rates and retail tenant credit.',
    narrative: 'Bond proxy; dead money until rates fall.',
    variantPerception: 'At 13.6× AFFO the market prices no growth; the platform has delivered 4–5% AFFO/share growth through two rate cycles. Income + modest growth beats the bond-proxy label.',
    bull: 'Rate relief re-rates the multiple; ~14% IRR.',
    base: '5.4% yield + 4% growth − multiple drift ≈ 8–9% IRR.',
    bear: 'Tenant credit event + higher-for-longer ≈ 2–3% total return.',
    assumptions: ['Dividend coverage ≥75% of AFFO', 'Tenant credit losses <1.5%/yr', 'Investment spreads ≥150bp'],
    reasonsToOwn: ['Monthly income matching household income goals', 'Below-median valuation on own history', 'Underwriting record across cycles'],
    reasonsNotToOwn: ['Rate direction dominates 1–2y returns', 'Drug/dollar tenant pressure', 'Growth requires equity markets to cooperate'],
    catalysts: [ { date: '2026-08-05', label: 'Q2 earnings + acquisitions guide', kind: 'earnings' } ],
    thesisBreakers: ['Dividend growth pause', 'Occupancy <97%', 'Spread <100bp on new investment'],
    leadingIndicators: ['10-yr real yields', 'Acquisition cap-rate spreads', 'Watchlist-tenant rent share'],
    valuationRange: { low: 48, high: 75 },
    expectedReturnPct: { y1: 9, y3: 25, y5: 42 },
    status: 'Hold',
    statusRationale: 'Held for the income sleeve; the Apr-2022 tax-lot harvest recommendation (see Meridian inbox) is a lot-level tax action, not a thesis change.',
  },
  news: [ { date: '2026-06-30', title: 'Announces $500M European sale-leaseback with grocery operator', source: { label: 'Company press (sample)', date: '2026-06-30', kind: 'sample_data' }, materiality: 'relevant', why: 'Confirms spread-investing capacity at ~180bp — above the assumption floor.' } ],
  qualityScores: [
    { key: 'managementCapital', label: 'Management & capital allocation', score: 7, basis: 'Transparent spread math; equity issuance discipline mostly maintained.' },
    { key: 'moat', label: 'Competitive advantage', score: 5, basis: 'Cost-of-capital moat — real but cyclical.' },
  ],
  snapshots: [ { date: '2026-05-04', status: 'Hold', note: 'Initiated: income holding; rate hostage acknowledged.' } ],
}
