'use client'
import * as React from 'react'
import Link from 'next/link'
import { cx } from '@/lib/util'

/* ---------------------------------------------------------------- Button */
type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'subtle'
type ButtonSize = 'sm' | 'md' | 'lg' | 'icon'
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean }

const base = 'inline-flex items-center justify-center gap-1.5 rounded-[9px] font-medium transition-all duration-150 select-none disabled:opacity-50 disabled:pointer-events-none whitespace-nowrap'
const variants: Record<ButtonVariant, string> = {
  primary: 'bg-accent text-accent-fg hover:bg-accent-hover shadow-[0_1px_0_rgba(0,0,0,0.05)]',
  secondary: 'bg-surface text-fg border border-border-2 hover:bg-surface-2',
  ghost: 'text-fg-2 hover:text-fg hover:bg-surface-2',
  subtle: 'bg-surface-2 text-fg hover:bg-surface-3',
  danger: 'text-danger hover:bg-danger/10',
}
// Touch screens get taller targets (pointer-coarse) without changing the desktop density.
const sizes: Record<ButtonSize, string> = { sm: 'h-7 px-2.5 text-[13px] pointer-coarse:h-9 pointer-coarse:px-3', md: 'h-8 px-3 text-[13.5px] pointer-coarse:h-10', lg: 'h-10 px-4 text-[15px] pointer-coarse:h-11', icon: 'h-8 w-8 p-0 pointer-coarse:h-10 pointer-coarse:w-10' }

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(function Button({ className, variant = 'secondary', size = 'md', loading, children, ...props }, ref) {
  return (
    <button ref={ref} className={cx(base, variants[variant], sizes[size], className)} {...props}>
      {loading ? <Spinner className="h-3.5 w-3.5" /> : null}
      {children}
    </button>
  )
})

export function Spinner({ className }: { className?: string }) {
  return (
    <svg className={cx('animate-spin', className ?? 'h-4 w-4')} viewBox="0 0 24 24" fill="none" aria-hidden>
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="2.5" opacity="0.2" />
      <path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
    </svg>
  )
}

/* ---------------------------------------------------------------- Inputs */
export const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(function Input({ className, ...props }, ref) {
  return <input ref={ref} className={cx('h-9 w-full rounded-[9px] border border-border-2 bg-surface px-3 text-[14px] placeholder:text-fg-3 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20 transition', className)} {...props} />
})

export const Textarea = React.forwardRef<HTMLTextAreaElement, React.TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({ className, ...props }, ref) {
  return <textarea ref={ref} className={cx('w-full rounded-[9px] border border-border-2 bg-surface px-3 py-2 text-[14px] placeholder:text-fg-3 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20 transition resize-none', className)} {...props} />
})

/* ---------------------------------------------------------------- Badges */
export function Badge({ children, tone = 'neutral', className }: { children: React.ReactNode; tone?: 'neutral' | 'accent' | 'success' | 'warning' | 'danger' | 'outline'; className?: string }) {
  const tones = {
    neutral: 'bg-surface-2 text-fg-2',
    accent: 'bg-accent-soft text-accent',
    success: 'bg-success/10 text-success',
    warning: 'bg-warning/10 text-warning',
    danger: 'bg-danger/10 text-danger',
    outline: 'border border-border text-fg-2',
  }
  return <span className={cx('inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[11.5px] font-medium leading-4 whitespace-nowrap', tones[tone], className)}>{children}</span>
}

export function Kbd({ children }: { children: React.ReactNode }) {
  return <kbd className="kbd">{children}</kbd>
}

export function AiMark({ className, label = 'AI' }: { className?: string; label?: string }) {
  return (
    <span suppressHydrationWarning className={cx('inline-flex items-center gap-1 text-[11px] font-semibold tracking-wide text-accent', className)} title="Generated by AI — traceable to sources">
      <span aria-hidden>✦</span>
      {label}
    </span>
  )
}

/* ---------------------------------------------------------------- Avatar */
export function Avatar({ name, size = 24, className }: { name: string; size?: number; className?: string }) {
  const initials = name.split(/\s+/).filter(Boolean).slice(0, 2).map((p) => p[0]!.toUpperCase()).join('')
  const hue = [...name].reduce((h, c) => (h * 31 + c.charCodeAt(0)) % 360, 7)
  return (
    <span className={cx('inline-flex shrink-0 items-center justify-center rounded-full font-semibold text-white', className)} style={{ width: size, height: size, fontSize: Math.max(9, size * 0.4), background: `oklch(0.55 0.09 ${hue})` }} aria-hidden>
      {initials}
    </span>
  )
}

/* ---------------------------------------------------------------- Layout */
export function PageHeader({ title, subtitle, actions, children, className }: { title: React.ReactNode; subtitle?: React.ReactNode; actions?: React.ReactNode; children?: React.ReactNode; className?: string }) {
  return (
    <header className={cx('mb-6 flex flex-col gap-3', className)}>
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <h1 className="text-[26px] font-semibold leading-tight tracking-[-0.02em] sm:text-[30px]">{title}</h1>
          {subtitle ? <p className="mt-1 text-[14px] text-fg-2">{subtitle}</p> : null}
        </div>
        {actions ? <div className="flex shrink-0 items-center gap-2">{actions}</div> : null}
      </div>
      {children}
    </header>
  )
}

export function Section({ title, action, children, className, count, hint }: { title: React.ReactNode; action?: React.ReactNode; children: React.ReactNode; className?: string; count?: number; hint?: string }) {
  return (
    <section className={cx('mb-8', className)}>
      <div className="mb-2.5 flex items-baseline justify-between gap-3">
        <h2 className="flex items-baseline gap-2 text-[13px] font-semibold uppercase tracking-[0.06em] text-fg-2">
          {title}
          {typeof count === 'number' ? <span className="text-[12px] font-medium normal-case tracking-normal text-fg-3">{count}</span> : null}
          {hint ? <span className="text-[12px] font-normal normal-case tracking-normal text-fg-3">{hint}</span> : null}
        </h2>
        {action}
      </div>
      {children}
    </section>
  )
}

export function EmptyState({ icon, title, description, action, className }: { icon?: React.ReactNode; title: string; description?: React.ReactNode; action?: React.ReactNode; className?: string }) {
  return (
    <div className={cx('flex flex-col items-center justify-center rounded-xl border border-dashed border-border-2 px-6 py-12 text-center', className)}>
      {icon ? <div className="mb-3 text-fg-3">{icon}</div> : null}
      <p className="text-[15px] font-medium">{title}</p>
      {description ? <p className="mt-1 max-w-sm text-[13.5px] text-fg-2">{description}</p> : null}
      {action ? <div className="mt-4">{action}</div> : null}
    </div>
  )
}

export function Skeleton({ className }: { className?: string }) {
  return <div className={cx('skeleton', className)} />
}

export function Divider({ className }: { className?: string }) {
  return <hr className={cx('border-border', className)} />
}

/* ---------------------------------------------------------------- Tabs (link-based) */
export function LinkTabs({ tabs, active, className }: { tabs: { id: string; label: string; href: string; count?: number }[]; active: string; className?: string }) {
  return (
    <nav className={cx('no-scrollbar -mx-5 flex gap-1 overflow-x-auto border-b border-border px-5 sm:mx-0 sm:px-0', className)} aria-label="Views">
      {tabs.map((t) => (
        <Link key={t.id} href={t.href} className={cx('-mb-px flex items-center gap-1.5 whitespace-nowrap border-b-2 px-2.5 py-2 text-[13.5px] transition pointer-coarse:py-2.5', active === t.id ? 'border-fg text-fg font-medium' : 'border-transparent text-fg-2 hover:text-fg')}>
          {t.label}
          {typeof t.count === 'number' && t.count > 0 ? <span className={cx('rounded px-1 text-[11px]', active === t.id ? 'bg-surface-3 text-fg-2' : 'bg-surface-2 text-fg-3')}>{t.count}</span> : null}
        </Link>
      ))}
    </nav>
  )
}

/* ---------------------------------------------------------------- Popover (hover / click) */
export function Popover({ trigger, children, align = 'start', className, openOn = 'hover' }: { trigger: React.ReactNode; children: React.ReactNode; align?: 'start' | 'end' | 'center'; className?: string; openOn?: 'hover' | 'click' }) {
  const [open, setOpen] = React.useState(false)
  const ref = React.useRef<HTMLDivElement>(null)
  const timer = React.useRef<number | undefined>(undefined)
  React.useEffect(() => {
    if (!open || openOn !== 'click') return
    const onDoc = (e: MouseEvent) => {
      if (!ref.current?.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    return () => document.removeEventListener('mousedown', onDoc)
  }, [open, openOn])
  const hoverProps = openOn === 'hover' ? {
    onMouseEnter: () => { window.clearTimeout(timer.current); timer.current = window.setTimeout(() => setOpen(true), 180) },
    onMouseLeave: () => { window.clearTimeout(timer.current); timer.current = window.setTimeout(() => setOpen(false), 120) },
  } : { onClick: () => setOpen((o) => !o) }
  return (
    <div ref={ref} className="relative inline-flex" {...hoverProps}>
      {trigger}
      {open ? (
        <div className={cx('animate-pop absolute top-full z-40 mt-1.5 rounded-xl border border-border bg-surface p-3 shadow-pop', align === 'end' ? 'right-0' : align === 'center' ? 'left-1/2 -translate-x-1/2' : 'left-0', className)} onClick={(e) => e.stopPropagation()}>
          {children}
        </div>
      ) : null}
    </div>
  )
}

/* ---------------------------------------------------------------- Menu */
export function Menu({ trigger, items, align = 'end' }: { trigger: React.ReactNode; items: { label: string; onSelect?: () => void; href?: string; danger?: boolean; icon?: React.ReactNode; disabled?: boolean }[]; align?: 'start' | 'end' }) {
  const [open, setOpen] = React.useState(false)
  const ref = React.useRef<HTMLDivElement>(null)
  React.useEffect(() => {
    if (!open) return
    const onDoc = (e: MouseEvent) => { if (!ref.current?.contains(e.target as Node)) setOpen(false) }
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false) }
    document.addEventListener('mousedown', onDoc)
    document.addEventListener('keydown', onKey)
    return () => { document.removeEventListener('mousedown', onDoc); document.removeEventListener('keydown', onKey) }
  }, [open])
  return (
    <div ref={ref} className="relative inline-flex">
      <span onClick={() => setOpen((o) => !o)}>{trigger}</span>
      {open ? (
        <div className={cx('animate-pop absolute top-full z-40 mt-1 min-w-[180px] rounded-xl border border-border bg-surface p-1 shadow-pop', align === 'end' ? 'right-0' : 'left-0')} role="menu">
          {items.map((it, i) =>
            it.href ? (
              <Link key={i} href={it.href} className="flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-[13.5px] hover:bg-surface-2" onClick={() => setOpen(false)} role="menuitem">
                {it.icon}{it.label}
              </Link>
            ) : (
              <button key={i} disabled={it.disabled} className={cx('flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-left text-[13.5px] hover:bg-surface-2 disabled:opacity-50', it.danger && 'text-danger')} onClick={() => { setOpen(false); it.onSelect?.() }} role="menuitem">
                {it.icon}{it.label}
              </button>
            ),
          )}
        </div>
      ) : null}
    </div>
  )
}

/* ---------------------------------------------------------------- Toast */
type Toast = { id: number; text: string; tone?: 'neutral' | 'success' | 'danger' }
const ToastCtx = React.createContext<{ push: (t: Omit<Toast, 'id'>) => void } | null>(null)
export function ToastProvider({ children }: { children: React.ReactNode }) {
  const [toasts, setToasts] = React.useState<Toast[]>([])
  const push = React.useCallback((t: Omit<Toast, 'id'>) => {
    const id = Date.now() + Math.random()
    setToasts((ts) => [...ts, { ...t, id }])
    window.setTimeout(() => setToasts((ts) => ts.filter((x) => x.id !== id)), 2600)
  }, [])
  return (
    <ToastCtx.Provider value={{ push }}>
      {children}
      <div className="pointer-events-none fixed bottom-20 left-1/2 z-[100] flex -translate-x-1/2 flex-col items-center gap-2 md:bottom-6">
        {toasts.map((t) => (
          <div key={t.id} className={cx('animate-up rounded-lg border border-border bg-surface px-3 py-2 text-[13px] shadow-pop', t.tone === 'success' && 'text-success', t.tone === 'danger' && 'text-danger')}>{t.text}</div>
        ))}
      </div>
    </ToastCtx.Provider>
  )
}
export function useToast() {
  const ctx = React.useContext(ToastCtx)
  return ctx ?? { push: () => undefined }
}

/* ---------------------------------------------------------------- Copy button */
export function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const [done, setDone] = React.useState(false)
  return (
    <Button size="sm" variant="ghost" onClick={async () => { try { await navigator.clipboard.writeText(text); setDone(true); setTimeout(() => setDone(false), 1500) } catch { /* ignore */ } }}>
      {done ? 'Copied' : label}
    </Button>
  )
}

/* ---------------------------------------------------------------- Simple markdown renderer (for AI outputs) */
export function Markdown({ text, className }: { text: string; className?: string }) {
  const html = React.useMemo(() => renderMarkdown(text), [text])
  return <div className={cx('prose-static text-[14px] leading-relaxed [&_mark]:rounded [&_mark]:bg-warning/25 [&_mark]:px-0.5 [&_table]:my-2 [&_table]:w-full [&_table]:text-[13px] [&_td]:border [&_td]:border-border [&_td]:px-2 [&_td]:py-1 [&_th]:border [&_th]:border-border [&_th]:bg-surface-2 [&_th]:px-2 [&_th]:py-1 [&_th]:text-left [&_a]:text-accent [&_a]:underline', className)} dangerouslySetInnerHTML={{ __html: html }} />
}

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
function inlineMd(s: string) {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*([^*\n]+)\*/g, '$1<em>$2</em>')
    .replace(/_([^_\n]+)_/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[(\d+)\]/g, '<a href="#cite-$1" data-cite="$1" class="cite">[$1]</a>')
    .replace(/\[([^\]]+)\]\((https?:[^)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>')
}
export function renderMarkdown(md: string): string {
  const lines = md.replace(/\r/g, '').split('\n')
  const out: string[] = []
  let i = 0
  while (i < lines.length) {
    const l = lines[i]!
    if (!l.trim()) { i++; continue }
    const h = l.match(/^(#{1,4})\s+(.*)$/)
    if (h) { out.push(`<h${h[1]!.length + 1} class="font-semibold mt-3 mb-1">${inlineMd(h[2]!)}</h${h[1]!.length + 1}>`); i++; continue }
    if (/^\|/.test(l)) {
      const rows: string[] = []
      while (i < lines.length && /^\|/.test(lines[i]!)) { const cells = lines[i]!.split('|').slice(1, -1).map((c) => c.trim()); if (!cells.every((c) => /^:?-+:?$/.test(c))) rows.push(cells.map((c, ci) => rows.length === 0 ? `<th>${inlineMd(c)}</th>` : `<td>${inlineMd(c)}</td>`).join('')); i++ }
      out.push(`<table>${rows.map((r) => `<tr>${r}</tr>`).join('')}</table>`); continue
    }
    if (/^\s*[-*•]\s+\[[ xX]\]\s+/.test(l)) {
      const items: string[] = []
      while (i < lines.length && /^\s*[-*•]\s+\[[ xX]\]\s+/.test(lines[i]!)) { const m = lines[i]!.match(/^\s*[-*•]\s+\[([ xX])\]\s+(.*)$/)!; items.push(`<li class="flex gap-2"><span class="mt-0.5 inline-block h-3.5 w-3.5 shrink-0 rounded border border-border-2 ${m[1] !== ' ' ? 'bg-accent' : ''}"></span><span>${inlineMd(m[2]!)}</span></li>`); i++ }
      out.push(`<ul class="my-1 space-y-1 list-none pl-0">${items.join('')}</ul>`); continue
    }
    if (/^\s*[-*•]\s+/.test(l)) {
      const items: string[] = []
      while (i < lines.length && /^\s*[-*•]\s+/.test(lines[i]!)) { items.push(`<li>${inlineMd(lines[i]!.replace(/^\s*[-*•]\s+/, ''))}</li>`); i++ }
      out.push(`<ul class="my-1 list-disc pl-5 space-y-0.5">${items.join('')}</ul>`); continue
    }
    if (/^\s*\d+[.)]\s+/.test(l)) {
      const items: string[] = []
      while (i < lines.length && /^\s*\d+[.)]\s+/.test(lines[i]!)) { items.push(`<li>${inlineMd(lines[i]!.replace(/^\s*\d+[.)]\s+/, ''))}</li>`); i++ }
      out.push(`<ol class="my-1 list-decimal pl-5 space-y-0.5">${items.join('')}</ol>`); continue
    }
    if (/^>\s?/.test(l)) { out.push(`<blockquote class="border-l-2 border-border-2 pl-3 text-fg-2">${inlineMd(l.replace(/^>\s?/, ''))}</blockquote>`); i++; continue }
    const buf: string[] = []
    while (i < lines.length && lines[i]!.trim() && !/^(#{1,4}\s|\||\s*[-*•]\s|\s*\d+[.)]\s|>)/.test(lines[i]!)) buf.push(lines[i++]!)
    out.push(`<p>${inlineMd(buf.join(' '))}</p>`)
  }
  return out.join('\n')
}
