/*
  The glossary behind every hover explainer in the app. Written for someone
  with a basic understanding of shares and options — plain language, one idea
  per paragraph, always tied back to what THIS app does with the concept.

  Entries are plain data so both server pages and client components can use
  them. Keep the tone factual: explain, never advise.
*/

export interface GlossaryEntry {
  title: string
  paragraphs: string[]
  example?: string
}

export const GLOSSARY = {
  /* ------------------------------- pages -------------------------------- */

  page_home: {
    title: 'How this screen works',
    paragraphs: [
      'This whole app is one weekly loop. Monday to Thursday it holds — usually the big line says "Nothing to do", and that is the design working, not a missing feature. On Friday it switches to writing the week\'s option tickets. After the broker fills them, you log the real numbers.',
      'Each live position below is one options contract batch you have sold. The chip on the right is the app\'s judgement of it: Healthy means leave it alone; Watch means a rule is close to triggering; Close now means an exit rule has fired and the screen will show exactly one instruction until you act on it.',
      'The Discipline tiles at the bottom measure how well the process is being followed — not how much money it made. Profit is the output; following the rules is the input you actually control.',
    ],
    example:
      'A row like "MSFT 4 Sep 547.5C ×16" means: 16 sold call contracts on Microsoft, strike price $547.50, expiring 4 September.',
  },
  page_write: {
    title: 'The Friday sequence',
    paragraphs: [
      'Every Friday the week is written through five steps that cannot be skipped: close out what expires today, confirm which side to trade for each stock, approve or decline each generated ticket, check the risk limits, and stamp the week done.',
      'The tickets are generated by the rules, not composed by hand: the valuation gate decides whether you sell puts, calls, or both on each name, and the 5-delta rule picks the strike price. You only say yes or no.',
      'If Friday ends without the stamp, the app records a missed week on the scoreboard. Skipped weeks are the invisible cost of this strategy — counting them makes them visible.',
    ],
  },
  page_log: {
    title: 'Logging fills',
    paragraphs: [
      'A "fill" is the broker\'s confirmation that your order actually traded, and at what price. The app\'s numbers are models; the fill is reality. Logging it does three things: records the trade, tunes the app\'s volatility estimate for that stock using the real transacted price, and updates the scoreboard.',
      'You can pick an approved ticket to pre-fill the form, or upload a screenshot of the broker confirmation — the app reads it into the form for you to check. Nothing is saved until you press Save.',
      'If a fill breaks a rule (for example the delta was outside the 3–8 band), the app records that in the deviation ledger automatically. It does not stop you; it counts.',
    ],
  },
  page_scoreboard: {
    title: 'The Discipline Score',
    paragraphs: [
      'This scoreboard measures adherence, not profit. Each of the four components is a plain fraction: how many times the rule was followed, out of how many chances.',
      'Cadence: weeks written out of weeks available. Rule: tickets written inside the 3–8 delta band. Stop: losing calls closed the same day the stop rule fired. Capacity: shares that could have calls written against them that actually do.',
      'The monthly trend matters more than the level. In the 2026 record, the Rule score falling in August was the drift that later cost money — a falling bar here is the early warning.',
    ],
  },
  page_pnl: {
    title: 'Profit and loss — one level down',
    paragraphs: [
      'P&L lives below the discipline score on purpose: week to week you do not control it, so staring at it teaches nothing. What it can teach is one comparison — trades that followed the process versus trades that deviated from it.',
      'In the 2026 record, seven of the eight losing positions were deviations of one kind or another. That running comparison is the whole argument for the rules.',
    ],
  },
  page_deviations: {
    title: 'The deviation ledger',
    paragraphs: [
      'Every departure from the process becomes a row here: a trade outside the delta band, an overridden valuation gate, a skipped week, a stop not taken, a trade in a blocked name.',
      'Each row records three things: what the rule said, what actually happened, and — once known — the outcome in dollars. Rows with no dollar figure yet say "unresolved"; the number is never guessed.',
      'The copy does not moralise. The arithmetic is the argument.',
    ],
  },
  page_valuations: {
    title: 'The valuation gate',
    paragraphs: [
      'Selling a put is agreeing to BUY shares at the strike price. Selling a call against shares you own is agreeing to SELL them at the strike. So before writing anything, the only question is: at today\'s price, would you rather be a buyer or a seller of this business?',
      'Five separate inputs answer that — where the price sits in its 52-week range, what analysts think it is worth, how its P/E compares to its own history, how its dividend yield compares to its own history, and your own written view (which counts double). They are always shown separately, never blended into a mystery score.',
      'Cheap reads gate to puts only (you want to be a buyer). Expensive reads gate to calls only (happy to be trimmed). Fair allows both — and fair should be the common state. Fewer than three filled inputs means "Insufficient data" and the gate defaults to both sides rather than pretending to know.',
      'The gate picks the SIDE only. The strike price always comes from the delta rule — valuation may shade it slightly, never past 8 delta.',
    ],
  },
  page_backtest: {
    title: 'Running the gate backwards',
    paragraphs: [
      'This page replays the valuation gate over the real early-2026 record: Microsoft fell from $505 to $357 and the book kept selling calls into the decline — agreeing again and again to sell shares cheaper — then sold 1,472 shares about 2% above the yearly low.',
      'At those prices the gate reads deep value → puts only, and blocks every one of those call tickets. It also shows where the gate would have been WRONG: many blocked calls were winners. The gate trades small premiums away to avoid selling a bottom. That trade-off is shown so it is chosen, not discovered.',
    ],
  },
  page_owl: {
    title: 'Why OWL is different',
    paragraphs: [
      'OWL is 28% of the whole portfolio — nearly double the 15% concentration limit. Owning too much of one thing is the risk here, so for OWL, being forced to sell shares (being "called away") is the desired outcome, not a loss.',
      'This sleeve writes longer-dated calls (30–45 days) at a higher delta (15–20) than the weekly programme. Each cycle collects premium for waiting, and carries a real chance of selling a block of shares at a price about 12% above today\'s — chosen in advance.',
      'OWL puts are blocked outright: selling a put risks buying MORE of the position that is already too big.',
    ],
  },
  page_position: {
    title: 'Reading this position',
    paragraphs: [
      'This page explains a decision already made — it is depth, not a place to find new trades. Everything here describes the one position at the top.',
      'The key number is the modelled mid versus the credit received. You sold this contract for the credit; the mid is roughly what it would cost to buy back today. Below 1× you are winning; at 0.2× the take-profit rule suggests closing; at 3× the stop rules fire.',
      'The payoff chart shows profit per share at every possible stock price. The cone chart shows where the model thinks the price could plausibly go before expiry, drawn over where it actually went.',
    ],
  },
  page_settings: {
    title: 'Settings',
    paragraphs: [
      'Three jobs live here: check that the app\'s external connections are configured (database, price fetching, WhatsApp alerts), test the alert pipe, and confirm your holdings.',
      'Confirming holdings matters more than it looks: every risk limit is computed from live portfolio value, and portfolio value is share counts × prices. Until a row is confirmed against the broker, its badge stays amber and the limits are estimates.',
    ],
  },

  /* ------------------------------ concepts ------------------------------- */

  covered_call: {
    title: 'Covered call',
    paragraphs: [
      'You own at least 100 shares and sell someone the right to buy them from you at a fixed price (the strike) before a fixed date (the expiry). They pay you cash now — the premium — which is yours to keep no matter what.',
      'If the stock stays below the strike, the option expires worthless and you simply keep the premium. If it rises above, your shares are sold at the strike: you still keep the premium, but you miss the gains above the strike.',
      'It is "covered" because you already own the shares you might have to deliver. Selling calls without the shares is naked — a position with unlimited risk, which this app blocks.',
    ],
    example: 'Own 1,600 MSFT shares, sell 16 calls at strike 547.50 for $37 each: collect $592 now; only obligation is selling at 547.50 if MSFT climbs that far.',
  },
  cash_secured_put: {
    title: 'Cash-secured put',
    paragraphs: [
      'You sell someone the right to sell you shares at a fixed price (the strike) before expiry, and you hold enough cash to buy them if it happens. They pay you a premium now, yours to keep regardless.',
      'If the stock stays above the strike, the option expires and the premium is pure income. If it falls below, you buy the shares at the strike — which only makes sense on stocks you would be glad to own at that price. That is why the valuation gate only allows puts on names that read fair or cheap.',
      'Being forced to buy is called assignment. In the 2026 record, all fourteen assignments ended up profitable — assignment is a plan here, never an accident.',
    ],
  },
  delta: {
    title: 'Delta',
    paragraphs: [
      'Delta is the model\'s estimate of the chance the option finishes "in the money" — the chance a sold call ends above its strike, or a sold put ends below. A 5-delta option has roughly a 5% modelled chance of being exercised, so about 95 weeks in 100 it expires worthless and the premium is kept.',
      'This programme\'s core rule: write between 3 and 8 delta. Lower collects too little to bother; higher is where the losses live. The August 2026 drift to 19, 31, even 36 delta felt fine because the premiums were fatter — that is exactly the trap the Rule score watches for.',
      'Delta is a model output, not a fact. The pre-mortem on each ticket also shows the historical base rate — how often the move actually happened recently — and flags loudly when history disagrees with the model.',
    ],
  },
  premium_credit: {
    title: 'Credit (premium)',
    paragraphs: [
      'The cash you receive for selling an option, quoted per contract. One contract covers 100 shares, so a quoted price of $0.37 per share is a $37 credit per contract; 16 contracts collect $592.',
      'The credit is banked the moment you sell. Every exit rule is measured against it: take profit when buying back costs 20% of it; stop a short call when buying back costs 3× it.',
    ],
  },
  strike: {
    title: 'Strike price',
    paragraphs: [
      'The fixed price written into the option contract: the price you agree to sell shares at (a call) or buy shares at (a put) if the buyer exercises.',
      'In this app you never choose strikes by feel — the math module solves for the strike whose delta matches the target (usually 5), then rounds it AWAY from the current price to the nearest listed increment, which keeps the real risk at or below the target.',
    ],
  },
  expiry: {
    title: 'Expiry',
    paragraphs: [
      'The date the option contract ends. After expiry it either exercises (shares change hands at the strike) or expires worthless (nothing happens, premium fully kept).',
      'The weekly programme sells options about 7 days out, every Friday. The OWL sleeve uses 30–45 days. Shorter contracts decay faster, which is the seller\'s friend.',
    ],
  },
  mid: {
    title: 'Modelled mid',
    paragraphs: [
      'Roughly what it would cost to buy the option back right now, per contract. "Mid" is midway between the buying and selling quotes on an exchange.',
      'Here the mid is MODELLED — computed by the Black-Scholes formula from the stored stock price and the volatility estimate, because this app deliberately has no market-data feed. That is why it renders with a dotted underline: check the real chain at the broker before acting on it.',
    ],
  },
  modelled: {
    title: 'What "modelled" means',
    paragraphs: [
      'Any number with a dotted underline was computed by a formula inside this app, not read from a live market. The formula (Black-Scholes) is the industry standard, but it is a simplification of reality — real quotes differ, sometimes a lot.',
      'The rule of the house: models decide when to LOOK; the broker\'s real chain decides what to DO. Always verify a modelled figure on the Fidelity chain before trading it.',
    ],
  },
  base_rate: {
    title: 'Historical base rate',
    paragraphs: [
      'The blunt question: in recent history, how often did this stock actually move far enough to breach this strike? The app slides a window over the stored daily prices and counts.',
      'This matters because the model\'s delta assumes calm, bell-curve behaviour. Real stocks jump. In mid-2026 the model said a 6.6% weekly MSFT move had ~5% odds, but it had actually happened in 8 of the last 45 windows (18%) — because MSFT once ran 25% in a week. When history says more than double the model, the ticket is flagged and needs an extra confirmation.',
      'Caveat, stated not hidden: these rates come from a few months of overlapping windows dominated by one event — "recent regime, small sample". They describe this stock lately, not forever.',
    ],
  },
  implied_vol: {
    title: 'Volatility (IV, realized, blended)',
    paragraphs: [
      'Volatility measures how much a stock tends to move, quoted as a yearly percentage. A 27% vol stock typically drifts a couple of percent in a week; a 140% vol stock can move that in an hour. Option prices depend on it directly: more expected movement = pricier options = fatter premiums but fatter risk.',
      'The app blends two sources: realized volatility (measured from the last 21 days of actual closing prices, 30% weight) and calibrated volatility (backed out of YOUR real logged fills, 70% weight). The calibrated leg dominates because a price someone actually paid beats any statistic.',
      'Until enough real fills accumulate, the calibrated leg uses the seed values — which were themselves solved from the 2026 fill history.',
    ],
  },
  obligation: {
    title: 'Obligation',
    paragraphs: [
      'For a sold put: the cash you would need if assigned — strike × 100 × contracts. Sell 10 puts at strike 482.50 and you are on the hook for up to $482,500 of stock purchases.',
      'The limits add these up: no more than $1.25m of total put obligation, no more than $400k on any single name. The Friday limits step blocks the week if a ticket would breach them.',
    ],
  },
  assignment: {
    title: 'Assignment',
    paragraphs: [
      'When the option buyer exercises their right: your sold put buys you shares at the strike; your sold call sells your shares at the strike. It mostly happens when the option finishes in the money at expiry.',
      'This programme treats assignment as a planned outcome, not an accident: puts are only sold on names cheap enough that buying at the strike is welcome, and in the OWL sleeve being called away IS the goal. All fourteen assignments in the 2026 record were profitable.',
    ],
  },
  coverage: {
    title: 'Coverage',
    paragraphs: [
      'One call contract obligates 100 shares. Coverage checks you actually own them: 1,752 MSFT shares cover at most 17 contracts. Writing an 18th would leave 48 shares\' worth of obligation naked — unlimited risk — so the app blocks it, and warns when a write uses every last coverable share.',
      'This is not theoretical: the historical META position sold 6 contracts against 547 shares. The 53 uncovered shares turned a routine trade into part of a $9,812 loss.',
    ],
  },
  greeks: {
    title: 'The greeks',
    paragraphs: [
      'Nicknames for how an option\'s price responds to change. Delta: chance of finishing in the money / sensitivity to the stock price. Theta: how much value the option loses per day just from time passing — income for the seller. Gamma: how fast delta itself grows if the stock moves toward the strike — the measure of how quickly a safe position can stop being safe. Vega: sensitivity to volatility rising.',
      'As a seller you are collecting theta while carrying gamma and vega risk. The exit rules exist because gamma can outrun theta in a single bad week.',
    ],
  },
  e_rules: {
    title: 'The exit rules (E1–E6)',
    paragraphs: [
      'Exits are deterministic — no judgement calls in the moment. E1: the option has decayed to 20% of the credit — buy it back, the remaining pennies are not worth the risk. E2: a sold CALL costs 3× the credit to buy back — close it the same session, no exceptions, no rolling. E3: a sold PUT reaches 3× — hold and prepare to take the shares (that was always the plan). E4: expires out of the money — do nothing. E5: delta drifted above 15 on what was a 5-delta write — the situation changed, review it. E6: the AI news check says the thesis broke — review immediately.',
      'E2 is the most important rule in the system, and "rolling" (closing a loser by opening a bigger one) does not exist in this app. Rolling is how a $600 loss became $9,812.',
    ],
  },
  l_limits: {
    title: 'The risk limits (L1–L8)',
    paragraphs: [
      'Hard caps computed from live portfolio value, checked every Friday before the week can be stamped: total put obligation ≤ $1.25m (L1); at most 12 open positions (L2); ≤ $400k put obligation on one name (L3); no single holding above 15% of the portfolio (L4); at most 5 different stocks with open options (L7); and two E2 stops in one week pauses all writing (L8).',
      'L4 is breached today by OWL (28%) and MSFT (17.5%) — which is why the OWL exit sleeve exists and why the breach banner never leaves the home screen.',
    ],
  },
  chips: {
    title: 'The chips',
    paragraphs: [
      'Each open position gets one word. Healthy: no rule is close; do nothing. Watch: a rule is nearby — profit-taking available (E1), a put moving toward assignment (E3), delta drifting (E5) — worth a look, not urgent. Close now: an urgent rule (E2 stop or a broken thesis) has fired; the home screen collapses to a single instruction until it is done.',
      'The chips are the whole Monday–Thursday interface on purpose. If everything says Healthy, the correct action is to close the tab.',
    ],
  },
  cadence: {
    title: 'Cadence score',
    paragraphs: [
      'Weeks written on schedule ÷ weeks available. The strategy\'s edge is showing up every Friday: each skipped week is premium never collected, invisible unless counted. The 2026 baseline was 32 of 35.',
      'A missed Friday is recorded automatically and permanently — it appears here and in the deviation ledger.',
    ],
  },
  rule_score: {
    title: 'Rule score',
    paragraphs: [
      'Tickets written inside the 3–8 delta band ÷ all tickets written. This is the drift detector: the rules do not usually break loudly, they erode — 5 delta becomes 9, becomes 19, becomes 36, each step justified by a fatter premium.',
      'Watch the monthly trend, not the level. August 2026 is the cautionary tale: the score fell exactly when the drift began, before it cost anything.',
    ],
  },
  stop_score: {
    title: 'Stop score',
    paragraphs: [
      'E2 stops taken the same session ÷ E2 stops triggered. When a sold call reaches 3× its credit, the rule says close it that day. This fraction measures whether that actually happens.',
      'It was never measured before this app existed — and the biggest loss in the record (the −$9,812 META roll) was precisely a stop not taken.',
    ],
  },
  capacity: {
    title: 'Capacity score',
    paragraphs: [
      'Of the shares you own that COULD have calls written against them (in names with a usable options market), how many actually do? Idle shares are premium not collected.',
      'The historic example: 120,000 OWL shares sat for years with not one call ever written. Only holdings with verified, liquid option chains count — owning something does not make it tradeable.',
    ],
  },
  band_gate: {
    title: 'Bands and gates',
    paragraphs: [
      'The five inputs combine into a band — deep value, undervalued, fair, rich, or overvalued — and the band sets the gate: cheap gates to puts only (assignment would be buying a bargain), expensive gates to calls only (being trimmed is welcome), fair allows both.',
      'You can override a gate, but only with a typed reason, and the override goes into the deviation ledger where its eventual dollar outcome will be recorded next to it.',
    ],
  },
  range_position: {
    title: '52-week range position',
    paragraphs: [
      'Where today\'s price sits between the stock\'s lowest and highest points of the last year. Near the low reads cheap-ish; near the high reads expensive-ish. It is the simplest of the five inputs — and the one that would have caught the Jan–Mar mistake, when calls were being sold 2% above the yearly low.',
      'Enter the 52-week low and high from any broker or finance site; the app computes the position from today\'s price.',
    ],
    example: 'MSFT at $513 with a $351–$568 yearly range sits at 75% of the range — the expensive end.',
  },
  analyst_target: {
    title: 'Analyst consensus target',
    paragraphs: [
      'The average 12-month price target published by the analysts covering the stock — shown on most broker and finance pages as "price target" or "consensus".',
      'A target well above today\'s price leans cheap; a price already above the target leans expensive. Analysts herd and lag, so this is one voice of five, not a verdict.',
    ],
  },
  pe_vs_median: {
    title: 'P/E versus its own history',
    paragraphs: [
      'The price-to-earnings ratio says how many dollars you pay for each dollar of yearly profit. Comparing it to other companies is noisy; comparing it to the SAME company\'s own typical level over ~5 years asks a cleaner question: is this business dearer or cheaper than it usually is?',
      'Enter today\'s forward P/E and the stock\'s typical (median) P/E; the app computes the gap. For REITs, BDCs and fund-like holdings a P/E means nothing — use the yield input instead.',
    ],
  },
  yield_vs_median: {
    title: 'Dividend yield versus its own history',
    paragraphs: [
      'Dividend yield is the yearly cash payout as a percentage of the share price. Because yield = payout ÷ price, a yield ABOVE the stock\'s own typical level usually means the PRICE is below its typical level — cheap — and vice versa.',
      'This is the primary valuation input for income holdings (OWL, EPR, DEA, BAM, the BDCs and REITs), where earnings-based measures mislead.',
    ],
    example: 'A stock that usually yields 4% now yielding 5%: the yield is 25% above typical, which reads as the price being meaningfully below typical.',
  },
  thesis: {
    title: 'Your own view (counts double)',
    paragraphs: [
      'The judgement input: after everything you know about the business, does today\'s price look cheap or expensive? It is weighted double because you know things the statistics cannot.',
      'The price of that power is a written reason — a view without a rationale does not count as filled. The reason is stored with the snapshot, so future-you can see what present-you was thinking.',
    ],
  },
  deviation: {
    title: 'Deviation',
    paragraphs: [
      'Any action the rules said not to take: writing outside the delta band, overriding a gate, trading a blocked name, skipping a week, not taking a stop. The app records deviations rather than preventing them — you stay in charge, but everything is counted.',
      'Each deviation eventually gets its dollar outcome filled in. Over time the ledger produces the only comparison that matters: what following the process earned versus what departing from it cost.',
    ],
  },
  dte: {
    title: 'DTE — days to expiry',
    paragraphs: [
      'Simply the number of calendar days until the option contract ends. The weekly programme writes at ~7 DTE; the OWL exit sleeve writes at 30–45 DTE because its goal (an eventual share sale at a good price) benefits from more time and a higher strike.',
    ],
  },
  trim_chance: {
    title: 'Chance of being trimmed',
    paragraphs: [
      'Roughly the option\'s delta read as a probability: a 17-delta call has about a 17% modelled chance of finishing above its strike, in which case the shares are sold ("called away") at that strike.',
      'In the OWL sleeve that outcome is the point: each cycle is paid waiting, with about a one-in-five chance of trimming an oversized position at a price ~12% above today\'s, chosen in advance.',
    ],
  },
  pre_mortem: {
    title: 'The pre-mortem',
    paragraphs: [
      'Before approving any ticket you see, in one sentence, exactly what has to happen for it to lose: the price move required, the model\'s odds of it, and — crucially — how often that move actually happened in recent history.',
      'When history disagrees with the model by more than 2×, the ticket is flagged and demands an extra confirmation. The model describes an idealized world; the base rate describes this stock in this market.',
    ],
  },
} as const satisfies Record<string, GlossaryEntry>

export type GlossaryKey = keyof typeof GLOSSARY
