/*
  Proactive observations, computed from the graph rather than generated by a
  model, so they are always grounded. Surfaced quietly on Home and entity pages.
*/
import { and, eq, gte, inArray, sql } from 'drizzle-orm'
import { getDb, schema } from './db'
import { uid, addDays, pluralize } from './util'

interface Candidate { kind: string; text: string; entityId?: string; score: number; evidence: { noteId: string; title: string }[]; dedupeKey: string }

export async function refreshInsights(contextId: string): Promise<void> {
  const db = await getDb()
  const now = new Date()
  const since30 = addDays(now, -30)
  const month = `${now.getFullYear()}-${now.getMonth() + 1}`
  const candidates: Candidate[] = []

  const notes = await db
    .select({ id: schema.notes.id, title: schema.notes.title, createdAt: schema.notes.createdAt })
    .from(schema.notes)
    .where(and(eq(schema.notes.contextId, contextId), gte(schema.notes.createdAt, since30), sql`${schema.notes.deletedAt} is null`))
  const noteIds = notes.map((n) => n.id)
  const titleOf = new Map(notes.map((n) => [n.id, n.title || 'Untitled']))
  if (noteIds.length) {
    const mentions = await db
      .select({ noteId: schema.noteEntities.noteId, entityId: schema.noteEntities.entityId, type: schema.entities.type, name: schema.entities.name })
      .from(schema.noteEntities)
      .innerJoin(schema.entities, eq(schema.entities.id, schema.noteEntities.entityId))
      .where(inArray(schema.noteEntities.noteId, noteIds))
    const byEntity = new Map<string, { name: string; type: string; notes: Set<string> }>()
    const companiesByNote = new Map<string, Set<string>>()
    for (const m of mentions) {
      const rec = byEntity.get(m.entityId) ?? { name: m.name, type: m.type, notes: new Set<string>() }
      rec.notes.add(m.noteId)
      byEntity.set(m.entityId, rec)
      if (m.type === 'company' && m.name.toLowerCase() !== (process.env.HOME_COMPANY || 'Google Cloud').toLowerCase()) {
        const s = companiesByNote.get(m.noteId) ?? new Set<string>()
        s.add(m.entityId)
        companiesByNote.set(m.noteId, s)
      }
    }
    for (const [entityId, rec] of byEntity) {
      if (rec.type !== 'topic') continue
      const companies = new Set<string>()
      for (const n of rec.notes) for (const c of companiesByNote.get(n) ?? []) companies.add(c)
      if (rec.notes.size >= 3 && companies.size >= 2) {
        candidates.push({
          kind: 'pattern',
          text: `You've discussed ${rec.name} in ${rec.notes.size} conversations across ${pluralize(companies.size, 'company', 'companies')} this month.`,
          entityId,
          score: Math.min(1, 0.4 + rec.notes.size * 0.1),
          evidence: [...rec.notes].slice(0, 6).map((id) => ({ noteId: id, title: titleOf.get(id) ?? '' })),
          dedupeKey: `pattern:${entityId}:${month}`,
        })
      }
    }
  }

  const openTasks = await db
    .select({ entityId: schema.tasks.entityId, name: schema.entities.name, type: schema.entities.type, n: sql<number>`count(*)`, sourceNoteId: sql<string>`min(${schema.tasks.sourceNoteId})` })
    .from(schema.tasks)
    .innerJoin(schema.entities, eq(schema.entities.id, schema.tasks.entityId))
    .where(and(eq(schema.tasks.contextId, contextId), inArray(schema.tasks.status, ['open', 'waiting', 'delegated'])))
    .groupBy(schema.tasks.entityId, schema.entities.name, schema.entities.type)
  for (const t of openTasks) {
    const n = Number(t.n)
    if (n >= 3 && t.entityId) {
      candidates.push({ kind: 'unresolved', text: `${pluralize(n, 'action')} from your ${t.name} conversations remain unresolved.`, entityId: t.entityId, score: Math.min(1, 0.5 + n * 0.08), evidence: t.sourceNoteId ? [{ noteId: t.sourceNoteId, title: titleOf.get(t.sourceNoteId) ?? 'Source note' }] : [], dedupeKey: `unresolved:${t.entityId}:${n}` })
    }
  }

  const promised = await db
    .select()
    .from(schema.commitments)
    .where(and(eq(schema.commitments.contextId, contextId), eq(schema.commitments.status, 'open'), eq(schema.commitments.kind, 'promised')))
  for (const c of promised) {
    const days = Math.floor((now.getTime() - c.detectedAt.getTime()) / 86400000)
    if (days >= 3) {
      candidates.push({ kind: 'overdue', text: `You committed to "${shorten(c.text)}" ${days === 1 ? 'yesterday' : `${days} days ago`} and it is still open.`, entityId: c.companyEntityId ?? c.counterpartyEntityId ?? undefined, score: Math.min(1, 0.5 + days * 0.05), evidence: c.sourceNoteId ? [{ noteId: c.sourceNoteId, title: titleOf.get(c.sourceNoteId) ?? 'Source note' }] : [], dedupeKey: `overdue:${c.id}` })
    }
  }

  const changes = await db.select().from(schema.changes).where(and(eq(schema.changes.contextId, contextId), gte(schema.changes.detectedAt, addDays(now, -14))))
  for (const ch of changes) {
    candidates.push({ kind: 'change', text: `Changed: ${ch.description}.`, entityId: ch.entityId ?? undefined, score: 0.7, evidence: [ch.sourceNoteId && { noteId: ch.sourceNoteId, title: titleOf.get(ch.sourceNoteId) ?? 'Source note' }, ch.previousNoteId && { noteId: ch.previousNoteId, title: titleOf.get(ch.previousNoteId) ?? 'Previous note' }].filter(Boolean) as { noteId: string; title: string }[], dedupeKey: `change:${ch.id}` })
  }

  for (const c of candidates) {
    await db
      .insert(schema.insights)
      .values({ id: uid('ins'), contextId, kind: c.kind, text: c.text, entityId: c.entityId, score: c.score, evidence: c.evidence, dedupeKey: c.dedupeKey })
      .onConflictDoUpdate({ target: [schema.insights.contextId, schema.insights.dedupeKey], set: { text: c.text, score: c.score, evidence: c.evidence } })
  }
  // Retire insights whose condition no longer holds.
  const keys = new Set(candidates.map((c) => c.dedupeKey))
  const existing = await db.select({ id: schema.insights.id, dedupeKey: schema.insights.dedupeKey }).from(schema.insights).where(eq(schema.insights.contextId, contextId))
  const stale = existing.filter((e) => !keys.has(e.dedupeKey)).map((e) => e.id)
  if (stale.length) await db.delete(schema.insights).where(inArray(schema.insights.id, stale))
}

function shorten(s: string): string {
  const t = s.replace(/^(I'll|I will|We'll|We will)\s+/i, '').replace(/[.]+$/, '')
  return t.length > 70 ? t.slice(0, 68).trimEnd() + '…' : t
}
