import { getDb, schema } from '../lib/db'
import { sql, desc } from 'drizzle-orm'
async function main() {
  const db = await getDb()
  const ents = await db.select({ type: schema.entities.type, name: schema.entities.name, m: schema.entities.mentionCount, ctx: schema.entities.contextId, attrs: schema.entities.attributes }).from(schema.entities).orderBy(schema.entities.type, desc(schema.entities.mentionCount))
  console.log('ENTITIES', ents.length)
  for (const e of ents) console.log(' ', e.type.padEnd(8), e.name.padEnd(32), e.m, e.ctx.slice(4), JSON.stringify(e.attrs))
  const tasks = await db.select({ t: schema.tasks.title, o: schema.tasks.owner, due: schema.tasks.dueAt, s: schema.tasks.status }).from(schema.tasks)
  console.log('TASKS', tasks.length)
  for (const t of tasks) console.log(' ', `[${t.s}]`, t.o, '→', t.t, t.due ? '(due ' + t.due.toDateString() + ')' : '')
  const decs = await db.select({ t: schema.decisions.title, s: schema.decisions.statement, st: schema.decisions.status }).from(schema.decisions)
  console.log('DECISIONS', decs.length)
  for (const d of decs) console.log(' ', `[${d.st}]`, d.t, '::', d.s.slice(0, 90))
  const revs = await db.select({ n: sql<number>`count(*)` }).from(schema.decisionRevisions)
  console.log('REVISIONS', revs[0]?.n)
  const cmts = await db.select({ t: schema.commitments.text, k: schema.commitments.kind, by: schema.commitments.byWhom }).from(schema.commitments)
  console.log('COMMITMENTS', cmts.length)
  for (const c of cmts) console.log(' ', `[${c.k}]`, c.by, '→', c.t.slice(0, 100))
  const facts = await db.select({ l: schema.facts.label, v: schema.facts.value, e: schema.entities.name, sup: schema.facts.supersededById }).from(schema.facts).innerJoin(schema.entities, sql`${schema.entities.id} = ${schema.facts.entityId}`)
  console.log('FACTS', facts.length)
  for (const f of facts) console.log(' ', f.e, '·', f.l, '=', f.v, f.sup ? '(superseded)' : '')
  const ch = await db.select({ d: schema.changes.description }).from(schema.changes)
  console.log('CHANGES', ch.length)
  for (const c of ch) console.log(' ', c.d)
  const ins = await db.select({ t: schema.insights.text, k: schema.insights.kind }).from(schema.insights)
  console.log('INSIGHTS', ins.length)
  for (const i of ins) console.log(' ', `[${i.k}]`, i.t)
  const notes = await db.select({ t: schema.notes.title, s: schema.notes.summary, err: schema.notes.processingError }).from(schema.notes)
  for (const n of notes) if (n.err) console.log('ERR', n.t, n.err)
  const s = notes.find((n) => n.t === 'Nissan — CFO meeting')
  console.log('SUMMARY nissan cfo', JSON.stringify(s?.s, null, 1))
}
main().then(() => process.exit(0))
