import type { Expansion } from './types.ts'

/**
 * Blue Owl Capital (NYSE: OWL) — the v3 chapters: history since founding, the multiple's
 * own history, the wide peer group, and the bond-yield comparison. Cut 20 September 2026.
 *
 * Year-end prices for 2021–2024 are tier B: derived from the total-return index the
 * company publishes in its 10-K (14 Dec 2020 = 100) less the dividends paid in each year.
 * Each carries roughly ±$0.30 of error from the dividend timing and the index rounding.
 */
export const OWL_EXPANSION: Expansion = {
  asOf: '2026-09-20',

  history: {
    provenance: [
      { when: '2011', event: 'Dyal Capital Partners formed inside Neuberger Berman by Michael Rees; Fund I raises $1.3bn to buy minority stakes in hedge-fund managers, later private-equity firms.', evidence: 'The GP-stakes franchise is a decade older than the listed company and was built as a captive unit, not a public business — which matters for how its economics were later valued.', tier: 'C' },
      { when: '2015–2020', event: 'Dyal II reports a 24% net IRR early in its life; Dyal III (2015 vintage) a 26% net IRR; Dyal IV closes at a record $9.0bn (2019–20) with stakes in HPS, Golub, Clearlake, H.I.G. and Owl Rock itself, marketed at a 34% IRR.', evidence: 'The pre-listing track record of the crown-jewel platform is genuinely strong. Note the circularity: Dyal owned a stake in Owl Rock before the two merged.', tier: 'C' },
      { when: '2016', event: 'Owl Rock founded by Doug Ostrover (GSO co-founder), Marc Lipschultz (KKR) and Craig Packer (Goldman Sachs) to lend directly to US middle-market companies.', evidence: 'Five years from founding to a $12.5bn listing — the fee base was assembled at a speed that only a zero-rate decade permits.', tier: 'C' },
      { when: 'July 2019', event: 'Owl Rock Capital Corporation (now OBDC) lists on the NYSE. Its 2020 proxy reports an 11.8% IRR on realised investments since inception.', evidence: 'The flagship fund\'s only pre-listing performance evidence that reached us. Its NAV per share has since gone $15.26 (Dec 2024) → $14.26 (Jun 2026), −6.6% in eighteen months.', tier: 'A' },
      { when: '23 Dec 2020', event: 'Owl Rock and Dyal agree to combine and list through Altimar Acquisition Corp, an HPS-sponsored SPAC: ~$45bn of AUM, ~$12.5bn post-transaction equity value, ~$1.8bn of gross proceeds, 91% of AUM described as permanent capital, distributable earnings 100% from fee-related earnings.', evidence: 'The listing promise, in one sentence: a permanent-capital fee annuity. Two of its four adjectives have since weakened — see the scorecard below.', tier: 'A' },
      { when: '19–20 May 2021', event: 'Combination closes; Blue Owl begins trading on the NYSE with $52.5bn of AUM. Seller earn-outs vest on 21 July ($12.50 hurdle) and 3 November 2021 ($15.00 hurdle) — 50m units in total — within six months of listing and before a single full-year result.', evidence: 'The founders were paid the full earn-out on share-price momentum in a SPAC bull market, not on delivery. It is a structural reason the diluted count starts at ~1.3bn rather than lower.', tier: 'A' },
    ],
    promises: [
      { promise: '91% of AUM in permanent capital', source: 'Dec 2020 merger announcement; May 2021 Form 425', delivered: '85% of management fees in permanent-capital vehicles (LTM to Mar 2026); 93% in 2022', status: 'Behind plan', tier: 'A', note: 'The single characteristic the equity was sold on, and the one that eroded. Two mechanisms: acquired capital at lower permanence, and the discovery in 2026 that "perpetual" wealth vehicles are puttable at 5% a quarter.' },
      { promise: 'Distributable earnings 100% from fee-related earnings — "enhanced predictability"', source: 'Dec 2020 announcement', delivered: '~96% of DE recurring; FRE $1.57bn LTM', status: 'Met', tier: 'B', note: 'Kept. Blue Owl is still the most fee-centric large manager listed, which is why the peer discount is so hard to justify on quality grounds.' },
      { promise: 'Projected combined revenue of ~$1.31bn (2022E) and ~$1.66bn (2023E), a 24% CAGR', source: 'S-4 projection case, as surfaced', delivered: 'Reported revenue ~$1.37bn (2022) and $1.73bn (2023)', status: 'Exceeded', tier: 'C', note: 'The S-4 carries several projection cases and the search-surfaced figures could not be attributed to one of them with certainty, so this row is tier C. On its face the top line beat the deck by roughly 4% in each year — but with the help of Oak Street and Wellfleet, neither of which the deck assumed.' },
      { promise: 'EBITDA / FRE margin of 68–70% (2021E–2024E)', source: 'S-4 projection case, as surfaced', delivered: '58.5% FRE margin (Q2 2026); 58.3% for FY2025', status: 'Behind plan', tier: 'C', note: 'A ten-point miss, subject to the same attribution caveat and to a definition that may not match FRE exactly. The direction is not in doubt: the acquired platforms and the wealth-distribution build carried lower margins than the founding businesses.' },
      { promise: 'Quarterly dividend of approximately 85% of distributable earnings', source: '2021 S-1', delivered: '77% (2022), 90% (2023), 94% (2024), 107% (2025), 106% (LTM)', status: 'Behind plan', tier: 'A', note: 'The policy was later changed to a fixed annual dividend set on expected DE. The payout has exceeded 85% every year since 2023 and 100% since 2025.' },
      { promise: '~$12.5bn post-transaction market capitalisation at $10.00 a share', source: 'Dec 2020 announcement', delivered: '$15.5bn at $9.88 on ~1,569m economic shares; $39bn at the January 2025 peak', status: 'In line', tier: 'B', note: 'The company is worth 24% more than the deck said; the share is worth 1% less. The gap is the share count: ~1,315m at listing to ~1,569m now, +19%, most of it acquisition equity.' },
      { promise: 'Seller earn-outs at $12.50 and $15.00', source: 'Business-combination agreement', delivered: 'Both hurdles cleared and 50m units vested by 3 November 2021', status: 'Achieved by acquisition', tier: 'A', note: 'For the sellers, exceeded; for the public holder, the dilution was crystallised at the top of the SPAC cycle. The shares traded below $15.00 for most of the following three years.' },
    ],
    acquisitions: [
      { target: 'Oak Street Real Estate Capital (net lease)', closed: '29 Dec 2021', consideration: '$950m plus earn-outs up to ~$650m', funding: 'Cash and Class A shares', aumAcquired: '$10.8bn', tier: 'A', note: 'The first deal after listing and the largest until IPI. Created the Real Assets platform.' },
      { target: 'Wellfleet Credit Partners (CLOs)', closed: '1 Apr 2022', consideration: '~$140m: $108m cash at close, up to $15m cash and 940,668 shares in earn-outs', funding: 'Mostly cash', aumAcquired: '$6.5bn', tier: 'A' },
      { target: 'Par-Four Investment Management (CLOs); CHI', closed: '2023', consideration: 'Not disclosed', funding: 'Not disclosed', aumAcquired: 'Small', tier: 'C' },
      { target: 'Prima Capital Advisors (real-estate credit)', closed: '6 Jun 2024', consideration: '~$170m', funding: 'Cash and shares', aumAcquired: '~$10bn', tier: 'A' },
      { target: 'Kuvare Asset Management (insurance)', closed: '1 Jul 2024', consideration: '$750m', funding: '$325m cash + $425m Class A shares', aumAcquired: '~$20bn', tier: 'A', note: 'Plus a $250m preferred investment in Kuvare — the first balance-sheet exposure to an insurer.' },
      { target: 'Atalaya Capital Management (asset-based finance)', closed: '30 Sep 2024', consideration: '$450m plus earn-outs up to ~$350m', funding: '~$350m equity + ~$100m cash', aumAcquired: '~$10bn', tier: 'A' },
      { target: 'IPI Partners (digital infrastructure)', closed: '6 Jan 2025', consideration: '~$1.0bn', funding: '~80% equity, ~20% cash', aumAcquired: '$11bn+', tier: 'A', note: 'Brought sovereign-wealth LPs and the data-centre pipeline; the largest single issuance of equity since the earn-outs.' },
    ],
    acquisitionsNote:
      'Headline consideration of roughly $3.5bn (tier B, summing the disclosed figures), plus earn-outs of up to ~$1.0bn, for roughly $68bn of AUM — about a quarter of the $267bn added since listing. Something over half of it was paid in equity, which is why the diluted share count rose ~19% while buybacks totalled $79m. What the purchases earn is not disclosed; at the blended fee rates and margins implied by the platform mix, tier D arithmetic puts the acquired FRE run-rate near $350–400m, a pre-tax yield on cost of roughly 10–11% before any earn-out. Reasonable for a fee stream — and it was bought at fee rates that lowered the blended rate of the whole company, which is the part the aggregate growth figures do not show.',
    life: [
      { period: 'Dec 2020 (SPAC)', price: 10.0, dePs: null, dividendPs: null, sharesM: null, aum: 45, tier: 'A', note: 'Altimar trust value; the base of the company\'s own total-return index.' },
      { period: 'FY2021', price: 14.7, dePs: 0.23, dividendPs: null, sharesM: 1315, aum: 94.5, tier: 'B', note: 'Price derived from the 10-K index (147). DE is Q3 + Q4 only ($0.11 + $0.12); the Q4 run-rate annualises to $0.48. Dividends: $0.04 (Q2), $0.10 declared for Q4; Q3 not retrieved.' },
      { period: 'FY2022', price: 10.5, dePs: 0.6, dividendPs: 0.46, sharesM: null, aum: 138.2, tier: 'B', note: 'Index 109; total return −26%. Dividend $0.10 / $0.11 / $0.12 / $0.13 by quarter.' },
      { period: 'FY2023', price: 14.9, dePs: 0.62, dividendPs: 0.56, sharesM: null, aum: 165.7, tier: 'B', note: 'Index 160; total return +47%. Fixed $0.14 a quarter from 2023.' },
      { period: 'FY2024', price: 23.4, dePs: 0.77, dividendPs: 0.72, sharesM: null, aum: 251.1, tier: 'B', note: 'Index 259; total return +62%. Four acquisitions in the year.' },
      { period: 'FY2025', price: 14.99, dePs: 0.84, dividendPs: 0.9, sharesM: 1550, aum: 307.4, tier: 'C', note: '30 Dec 2025 close. Total return −33% from the January peak of $25.02 (close) / $26.73 (intraday, 24 Jan).' },
      { period: '18 Sep 2026', price: 9.88, dePs: 0.87, dividendPs: 0.92, sharesM: 1569, aum: 319.0, tier: 'C', note: 'DE is LTM to Q2 2026. Intraday low of the year $7.95 (2 Apr); lowest close $8.45 (6 Apr).' },
    ],
    lifeNote:
      'From the $10.00 SPAC price the public holder has received $9.88 of price and roughly $3.5 of dividends in five and three-quarter years — a total return near +34%, about 5% a year, through a period in which AUM went from $45bn to $319bn. From the first year-end as a listed company ($14.7, Dec 2021) the total return is roughly −10%. Distributable earnings per share, meanwhile, went from a $0.48 run-rate to $0.87: the earnings did what the deck said; the multiple did the rest.',
    regimes: [
      { period: 'May–Dec 2021', regime: 'Zero rates, SPAC exuberance', whatHappened: 'Listing at $10; both earn-out hurdles cleared by November; Oak Street agreed in October. Rates at zero, private credit raising at will.', priceMove: '$10.00 → ~$14.7 (+47% total return on the index)', tier: 'B' },
      { period: '2022', regime: 'The rate shock', whatHappened: 'Fed funds from 0 to 4.25–4.50%. Alternative managers de-rate as a group; Blue Owl grows DE per share to $0.60 and steps the dividend up each quarter regardless.', priceMove: '~$14.7 → ~$10.5 (−26% total return)', tier: 'B' },
      { period: '2023–2024', regime: 'The private-credit and wealth-channel boom', whatHappened: 'Non-traded BDCs and perpetual vehicles gather record flows; four acquisitions in 2024 alone; AUM $166bn → $251bn. The multiple expands faster than the earnings.', priceMove: '~$10.5 → ~$23.4 (+47%, then +62%)', tier: 'B' },
      { period: '2025', regime: 'Peak, then the first cracks', whatHappened: 'All-time high $25.02 (close) in January. The 52-week high of $19.29 is set on 18 September. Q3 results miss on 30 October (−4% to $15.86); the OBDC II / OBDC merger is terminated on 19 November and OBDC II\'s quarterly tenders lapse.', priceMove: '$23.4 → $14.99 (−33% total return)', tier: 'C' },
      { period: 'H1 2026', regime: 'The redemption cycle', whatHappened: '19 Feb: $1.4bn of loans sold from three funds and OBDC II ends regular quarterly liquidity (−6% on the day). 24 Feb: Deutsche Bank downgrade. March: the "$265bn private-credit meltdown". 2 Apr: intraday low $7.95; Q1 repurchase requests $5.4bn (OCIC 21.9%, OTIC 40.7%).', priceMove: '$14.99 → $7.95 low → $9.35 at the 30 July cut', tier: 'C' },
      { period: 'Q3 2026', regime: 'Relief, then relapse', whatHappened: 'Q2 beat and easing redemptions lift the shares 29.5% in four weeks to $12.11 (27 Aug). Then: Fed raises to 3.75–4.00% (16 Sep), the 10-year crosses 5%, sell-side targets are trimmed to $14.93 from $16.40, and the shares give back the entire move.', priceMove: '$9.35 → $12.11 → $9.88', tier: 'C' },
    ],
    verdict:
      'Read from founding, Blue Owl is two very different companies stapled together in a SPAC at the top of a rate cycle: a decade-old GP-stakes franchise with an excellent private track record, and a five-year-old direct lender whose growth model — perpetual wealth vehicles — was untested by a redemption cycle. The listing sold the combination as a permanent-capital annuity. The annuity part has been delivered: DE per share nearly doubled, and it is 96% recurring. The permanent part has not: the permanent-capital share fell eight points, the payout drifted past 100%, and 2026 revealed that the flagship vehicles are puttable. Every acquisition since has bought growth at a lower fee rate with equity. The share price has round-tripped to the listing price while the company tripled its earnings power — which is precisely what an investor should expect when a business is sold at 30× DE and re-priced to 11×, and precisely why the current multiple, not the operating history, is where the investment case now lives.',
  },

  multiple: {
    earningsLineMultiple: 12,
    points: [
      { label: 'FY2021', date: '2021-12-31', price: 14.7, dePs: 0.48, basis: 'Q4 2021 annualised', tier: 'B', note: 'First year-end. The first full-year DE is not available; the Q4 run-rate is the fairest denominator.' },
      { label: 'FY2022', date: '2022-12-30', price: 10.5, dePs: 0.6, basis: 'FY2022', tier: 'B' },
      { label: 'FY2023', date: '2023-12-29', price: 14.9, dePs: 0.62, basis: 'FY2023', tier: 'B' },
      { label: 'FY2024', date: '2024-12-31', price: 23.4, dePs: 0.77, basis: 'FY2024', tier: 'B' },
      { label: 'Peak', date: '2025-01-24', price: 25.02, dePs: 0.77, basis: 'FY2024', tier: 'C', note: 'Highest close, January 2025. Intraday high $26.73.' },
      { label: 'FY2025', date: '2025-12-30', price: 14.99, dePs: 0.84, basis: 'FY2025', tier: 'C' },
      { label: 'Low', date: '2026-04-06', price: 8.45, dePs: 0.86, basis: 'LTM Q1 26', tier: 'C', note: 'Lowest close. Intraday low $7.95 on 2 April.' },
      { label: 'Cut', date: '2026-07-30', price: 9.35, dePs: 0.87, basis: 'LTM Q2 26', tier: 'C' },
      { label: 'Aug pass', date: '2026-08-27', price: 12.11, dePs: 0.87, basis: 'LTM Q2 26', tier: 'C' },
      { label: 'Now', date: '2026-09-18', price: 9.88, dePs: 0.87, basis: 'LTM Q2 26', tier: 'C' },
    ],
    pointsNote:
      'Ten dated price / DE-per-share pairs; the multiple and the DE yield are derived. The earnings line is drawn at 12× — the base-case exit multiple — so that where the price sits relative to it is the question the chart asks. Year-end prices 2021–2024 are derived from the company\'s total-return index and carry ±$0.30; everything from 2025 is an aggregator close, tier C.',
    decomposition: [
      { term: 'DE per share', from: '$0.48 (Q4 2021 run-rate)', to: '$0.87 (LTM Q2 2026)', contribution: '+81%', effect: 'positive', note: 'The earnings leg did its job: a 13% compound rate through a rate shock, a boom and a redemption cycle.' },
      { term: 'Multiple (price / DE)', from: '30.6×', to: '11.4×', contribution: '−63%', effect: 'negative', note: 'The whole of the loss. The multiple has been as high as 32.5× (Jan 2025) and as low as 9.2× (2 Apr 2026, intraday) — a 3.5:1 range on the same earnings stream.' },
      { term: 'Price', from: '$14.7', to: '$9.88', contribution: '−33%', effect: 'negative', note: '1.81 × 0.37 = 0.67. The identity closes.' },
      { term: 'Dividends collected, 2022 – Sep 2026', from: '—', to: '$3.33 per share', contribution: '+23% of the starting price', effect: 'positive', note: '$0.46 + $0.56 + $0.72 + $0.90 + three quarters of $0.23. The dividend has done all the work of keeping the total return near zero.' },
      { term: 'Total return, Dec 2021 – Sep 2026', from: '$14.7', to: '$13.21 (price + dividends)', contribution: '−10% over 4.7 years, ≈ −2% a year', effect: 'negative', note: 'From the $10.00 SPAC price instead: +34%, about 5% a year — the listing price, not the first year-end, is the more flattering base and the one the company uses.' },
    ],
    decompositionNote:
      'The decomposition is the investment case in three lines. Earnings compounded at 13%; the multiple was cut by nearly two-thirds; the holder has been paid to wait. It also frames the two failure modes precisely: the bear case is that 11× is the right multiple for a puttable fee stream, in which case the return from here is the DE yield less the dividend cut; the base case is that 12× is the right multiple and the earnings leg carries the rest. Neither requires a return to the 2024 multiple, which was a boom-era number on a permanence claim that has since failed.',
    technicals: [
      { indicator: 'Position in the 52-week range', value: '17% ($7.95 – $19.29)', read: 'In the bottom fifth of the year\'s range after the September relapse.', tier: 'B' },
      { indicator: 'Drawdown from the all-time high close ($25.02, Jan 2025)', value: '−60.5%', read: 'Deeper than any listed alternative manager in the peer set; only the multiple, not the earnings, has fallen.', tier: 'B' },
      { indicator: 'Recovery from the record-low close ($8.45, 6 Apr 2026)', value: '+16.9%', read: 'The August rally (+43% from the low at its peak) has given back roughly two-thirds.', tier: 'B' },
      { indicator: 'Three-week momentum since the 27 August pass', value: '−18.4%', read: 'A move of this size on no company disclosure is sector and rates beta, not stock-specific information.', tier: 'B' },
      { indicator: '50/200-day weighted moving-average cross', value: 'Golden cross reported 14 Aug 2026', read: 'The cross was reported by a single secondary source and the shares have since fallen 18%; treat the signal as failed. Current moving-average levels were not retrievable through our sources.', tier: 'C' },
      { indicator: 'RSI(14)', value: 'Not retrievable', read: 'The only figure surfaced (33) dated from the first quarter, when the shares were $15; we do not carry stale technicals.', tier: 'D' },
      { indicator: 'Sell-side price targets', value: 'Average $14.93 (from $16.40); Barclays Hold, KBW Market Perform', read: 'Targets are converging on the price from above. FY2027 EPS estimates range from $1.30 to $1.71 — the dispersion is the more useful fact.', tier: 'C' },
    ],
    technicalsNote:
      'Chart technicals are shown for context and are not used in the rating. The two that carry information are the range position and the momentum since the last pass: together they say the shares have re-entered the zone in which they traded before the August re-rating, on a rates-driven sell-off rather than on company news. Everything else on this list is either derived from the price series above or could not be retrieved at the standard this memo requires.',
    verdict:
      'On its own history Blue Owl at 11.4× distributable earnings is near the bottom of its listed-life range — above only the April 2026 low and the July cut — against a range of 17.5–32.5× at every previous year-end. That is the whole bull argument, and it is also the trap: the year-end multiples were set by a market that believed the capital was permanent. A fair reading is that the pre-2025 range is not coming back, that a puttable-vehicle manager with a 106% payout warrants 10–12×, and that the stock is therefore fairly-to-modestly cheap on its own history rather than dramatically so. The base case has always said exactly that.',
  },

  peers: {
    rows: [
      { ticker: 'OWL', name: 'Blue Owl Capital', group: 'Subject', price: 9.88, marketCapBn: 15.5, freAnnualisedM: 1573, freGrowthPct: 9, freMarginPct: 58.5, pFre: 9.9, pDe: 11.4, divYieldPct: 9.3, permCapital: '85% of fees; flagship vehicles capped', creditSharePct: 53, tier: 'B', note: 'FRE is LTM, not annualised Q2. Highest margin, lowest growth, only uncovered dividend, only gated vehicles.' },
      { ticker: 'APO', name: 'Apollo Global Management', group: 'Credit-heavy', price: 127, marketCapBn: 74.3, freAnnualisedM: 2950, freGrowthPct: null, freMarginPct: null, pFre: 25.2, pDe: 15.0, divYieldPct: 1.8, permCapital: 'Very high — Athene insurance balance sheet', creditSharePct: 86, tier: 'C', note: 'Q2 2026 FRE $1.26/share, SRE $1.41, ANI $2.11; P/DE shown on ANI. Price from the 17 Sep range; market cap 14 Sep. The most credit-exposed manager in the group trades at the highest FRE multiple — because its permanent capital is an insurer\'s liabilities, not a retail fund\'s.' },
      { ticker: 'ARES', name: 'Ares Management', group: 'Credit-heavy', price: 124, marketCapBn: 38, freAnnualisedM: 1964, freGrowthPct: 20, freMarginPct: null, pFre: 19.3, pDe: null, divYieldPct: 4.4, permCapital: 'High', creditSharePct: 66, tier: 'D', note: 'Q2 2026 FRE $491m (+20%), AUM $671bn, FPAUM $410bn, dividend $1.35/quarter (+20%). Aggregator price snapshots this month range $105.80–$142.76 and market caps $31.6–45.7bn; the midpoint is shown and this is the least reliable row in the table. The 52-week range is $95.80–$186.85.' },
      { ticker: 'BX', name: 'Blackstone', group: 'Buyout-heavy', price: 124.96, marketCapBn: 157.3, freAnnualisedM: 7200, freGrowthPct: 22, freMarginPct: null, pFre: 21.8, pDe: 20.6, divYieldPct: 4.2, permCapital: 'High — perpetual vehicles, insurance', creditSharePct: null, tier: 'C', note: 'Q2 2026 FRE $1.8bn / $1.43 per share (+22%), DE $2.0bn / $1.52 (+26%), AUM $1.35tn. 18 Sep close. Market cap is price × the ~1,259m share count implied by FRE $1.8bn ÷ $1.43 — aggregator snapshots ranged $152–163bn. The scale benchmark.' },
      { ticker: 'KKR', name: 'KKR & Co.', group: 'Buyout-heavy', price: 98.81, marketCapBn: 90.9, freAnnualisedM: 4856, freGrowthPct: 34, freMarginPct: null, pFre: 18.7, pDe: 15.2, divYieldPct: 0.7, permCapital: 'High — Global Atlantic', creditSharePct: 48, tier: 'C', note: 'Q2 2026 FRE $1.214bn / $1.32 per share (+34%), ANI $1.63 (+38%); FEAUM $638bn. P/DE on ANI. 18 Sep close; market cap on the ~920m shares implied by FRE $1.214bn ÷ $1.32 (a 4 Sep aggregator snapshot said $96.7bn). Down 19.5% over a year.' },
      { ticker: 'BAM', name: 'Brookfield Asset Management', group: 'Buyout-heavy', price: 45.3, marketCapBn: 74.2, freAnnualisedM: 3232, freGrowthPct: 20, freMarginPct: null, pFre: 22.6, pDe: 25.9, divYieldPct: 4.4, permCapital: 'High — perpetual infrastructure and renewables', creditSharePct: null, tier: 'C', note: 'Q2 2026 FRE $808m / $0.50 per share (+20%), DE $0.44 (LTM $1.75). Dividend $0.5025/quarter. 52-week range $42.20–$62.57.' },
      { ticker: 'CG', name: 'The Carlyle Group', group: 'Buyout-heavy', price: 41.4, marketCapBn: 14.8, freAnnualisedM: 1432, freGrowthPct: 11, freMarginPct: null, pFre: 10.3, pDe: 9.7, divYieldPct: 3.4, permCapital: 'Moderate', creditSharePct: null, tier: 'C', note: 'Q2 2026 FRE $358m (+11%, a record), DE $472m / $1.07 (highest in four years), AUM $485bn. Price implied by the 3.38% yield on a $1.40 dividend. Down 30% year to date — the other cheap large manager, and cheap for a different reason: buyout realisations.' },
      { ticker: 'TPG', name: 'TPG Inc.', group: 'Buyout-heavy', price: 52.67, marketCapBn: 19.5, freAnnualisedM: 1260, freGrowthPct: 43, freMarginPct: 50, pFre: 15.5, pDe: 19.1, divYieldPct: 4.5, permCapital: 'Lower', creditSharePct: null, tier: 'D', note: 'Q2 2026 FRE $315m (+43%), margin 50% (from 44%), after-tax DE $0.69 per share, dividend $0.59/quarter, AUM $327bn. Price 5 Sep; market cap on all share classes is our estimate — the aggregator figure of $7.3bn is Class A only.' },
      { ticker: 'HLNE', name: 'Hamilton Lane', group: 'Solutions', price: 95.98, marketCapBn: 5.29, freAnnualisedM: 496, freGrowthPct: 49, freMarginPct: null, pFre: 10.7, pDe: 12.4, divYieldPct: 2.3, permCapital: 'Low', creditSharePct: null, tier: 'C', note: 'Q1 FY2027 FRE $124m (+49%) — lifted by a 170% rise in incentive fees, which Hamilton Lane includes in FRE, so the multiple flatters; adjusted EPS $1.94 (P/E ≈12×). Fee-earning AUM $83.7bn. Fee-only, no balance sheet.' },
      { ticker: 'STEP', name: 'StepStone Group', group: 'Solutions', price: 47.1, marketCapBn: 6.0, freAnnualisedM: 424, freGrowthPct: 30, freMarginPct: 39, pFre: 14.2, pDe: null, divYieldPct: 2.0, permCapital: 'Low', creditSharePct: null, tier: 'C', note: 'Q1 FY2027 FRE $106m (+30%), 39% margin; GAAP loss on a non-cash item. 18 Sep close; market cap across classes.' },
      { ticker: 'GCMG', name: 'GCM Grosvenor', group: 'Solutions', price: 13.86, marketCapBn: 2.8, freAnnualisedM: 201, freGrowthPct: 21, freMarginPct: 45, pFre: 13.9, pDe: null, divYieldPct: 3.5, permCapital: 'Low to moderate', creditSharePct: null, tier: 'C', note: 'Q2 2026 FRE $50.3m (+21%), 45% margin, AUM $97bn, FPAUM $78bn. Price 14 Aug — the stalest in the table.' },
      { ticker: 'VINP', name: 'Vinci Compass', group: 'Latin America', price: 9.55, marketCapBn: 0.63, freAnnualisedM: 69, freGrowthPct: 36, freMarginPct: 32.5, pFre: 9.1, pDe: 12.7, divYieldPct: 7.1, permCapital: 'Low', creditSharePct: null, tier: 'C', note: 'Q2 2026 FRE R$88.7m (+36%), R$1.35 per share, 32.5% margin; adjusted DE R$0.96 per share; dividend $0.17/quarter. Converted at USD/BRL 5.14. Price 10 Sep.' },
      { ticker: 'PAX', name: 'Patria Investments', group: 'Latin America', price: 11.17, marketCapBn: 1.77, freAnnualisedM: 228, freGrowthPct: 24, freMarginPct: 54, pFre: 7.5, pDe: 8.7, divYieldPct: 5.8, permCapital: '22% of FEAUM; no gates', creditSharePct: null, tier: 'B', note: 'Q2 2026 FRE $57.1m (+24%), 54.0% margin. P/FRE on the FY2026 guidance midpoint ($1.48), as in the companion memo; on annualised Q2 it is 7.8×. See the companion memo.' },
    ],
    rowsNote:
      'Thirteen names grouped by business model. Multiples are price over the latest reported quarter annualised (FRE) or the disclosed per-share figure (DE / ANI), so they are not seasonally adjusted and not consensus-based. Prices are aggregator snapshots from the week of 14–18 September unless the note says otherwise; where snapshots disagreed the row is tier D and says so. Petershill Partners — the only listed GP-stakes comparator for Blue Owl\'s GP Strategic Capital platform — is absent because it delisted in 2026; see below.',
    whatMarketPays: [
      { factor: 'Scale', evidence: 'The five managers above $35bn of market value (BX, KKR, BAM, APO, ARES) trade at 19–25× FRE. The eight below $20bn trade at 7.5–16×.', verdict: 'Explains more of the cross-section than any operating metric. Index and flow-driven ownership buys the largest names first.' },
      { factor: 'FRE growth', evidence: 'The two fastest organic growers in the set — Vinci (+36%) and Patria (+24%) — are the two cheapest. TPG (+43%) is mid-table at 15.5×; KKR (+34%) is 18.7×.', verdict: 'Growth is paid for only above the scale threshold. Below it, it is discounted for where it comes from.' },
      { factor: 'FRE margin', evidence: 'Blue Owl has the highest margin (58.5%) at the second-lowest multiple; Patria\'s 54% earns the lowest; TPG\'s 50% earns 15.5×.', verdict: 'Margin is not what the market is paying for in 2026. It was in 2024.' },
      { factor: 'Credit exposure', evidence: 'The four credit-heaviest managers — APO 86%, ARES 66%, OWL 53%, KKR 48% of fee-earning assets — span 10–25×.', verdict: 'Credit exposure per se does not set the multiple. Where the credit capital sits does: insurance balance sheets (APO, KKR) at the top, capped retail vehicles (OWL) at the bottom.' },
      { factor: 'Liability structure', evidence: 'Blue Owl is the only name with flagship vehicles fulfilling a quarter of redemption requests, and the only name near 10× with a 58% margin.', verdict: 'The gate is the discount. Everything else about Blue Owl argues for a higher multiple.' },
      { factor: 'Payout', evidence: 'Dividend yields run 0.7% (KKR) to 4.5% (TPG, BAM) across the group; Blue Owl\'s 9.3% on a 106% payout stands alone.', verdict: 'A yield twice the group\'s is priced as a cut, not a reward. It is also the single cheapest thing for management to fix.' },
      { factor: 'Domicile', evidence: 'The two Latin American managers trade at 7.5–9× on the fastest growth in the set.', verdict: 'The discount is roughly the Brazilian sovereign spread plus a governance and disclosure premium — see the companion memo and §22 there.' },
    ],
    delisting:
      'Petershill Partners, Goldman Sachs\' listed GP-stakes vehicle and the only public comparator for Blue Owl\'s GP Strategic Capital platform, delisted from the London Stock Exchange in 2026 at a $4.5bn valuation, returning $921m to free-float holders at a premium of roughly 35% to the prior close, citing low trading volumes, a limited free float and a public market that "failed to capture the asset class\'s full worth". Two readings, both relevant here. First, the private mark for a GP-stakes book was materially above the public one — supportive of the 16× FRE we apply to the GP Strategic Capital stream in the sum-of-the-parts, which the market does not appear to pay. Second, the liquidity of GP stakes themselves is the asset class\'s weak point: Dyal shelved a GP-led process on Fund III in favour of a $1bn securitisation, and Blue Owl has sought a $1.5bn secondary sale from Dyal IV. A stream whose underlying assets need structuring to be sold is permanent for the manager and illiquid for the fund investor — which is the right way to read "permanent capital" here.',
    verdict:
      'Across thirteen listed managers the market in September 2026 is paying for scale first, for insurance-backed permanence second, and for liability structure third; it is not paying for margin and it is not paying for growth below a size threshold. Blue Owl fails the first test, is on the wrong side of the second, and is the group\'s clearest example of the third. On the metrics the memo values — margin, fee rate, recurring share — it is the highest-quality fee stream in the bottom half of the table. The warranted multiple this analysis has carried since July, 12–13×, sits at the midpoint between where the market puts Blue Owl and where it puts the other credit-heavy managers, and that is where it stays.',
  },

  yields: {
    rows: [
      { instrument: 'Blue Owl — distributable-earnings yield', yieldPct: 8.8, asOf: '18 Sep 2026', basis: 'LTM DE $0.87 ÷ $9.88', kind: 'subject', tier: 'B' },
      { instrument: 'Blue Owl — fee-related-earnings yield', yieldPct: 10.2, asOf: '18 Sep 2026', basis: 'LTM FRE $1.01 ÷ $9.88; pre-interest, pre-tax', kind: 'subject', tier: 'B' },
      { instrument: 'Blue Owl — dividend yield (106% payout)', yieldPct: 9.3, asOf: '18 Sep 2026', basis: '$0.92 declared ÷ $9.88', kind: 'subject', tier: 'B' },
      { instrument: 'OBDC — dividend yield on price', yieldPct: 11.4, asOf: '15 Sep 2026', basis: '$1.26 annual ÷ $11.08; the manager\'s listed flagship fund', kind: 'fund', tier: 'C' },
      { instrument: 'OBDC — dividend yield on NAV', yieldPct: 9.3, asOf: '30 Jun 2026', basis: '$0.33 quarterly ÷ $14.26 NAV; shares at 0.78× NAV', kind: 'fund', tier: 'A' },
      { instrument: 'Cliffwater Direct Lending Index — interest income', yieldPct: 10.4, asOf: 'CY2025', basis: 'Income yield of ~$549bn of US middle-market loans; total return 9.3% in 2025, 7.7% trailing year to Jun 2026', kind: 'private', tier: 'C' },
      { instrument: 'ICE BofA CCC & lower', yieldPct: 14.9, asOf: '3 Sep 2026', basis: 'Effective yield', kind: 'credit', tier: 'C' },
      { instrument: 'ICE BofA single-B', yieldPct: 7.27, asOf: '3 Sep 2026', basis: 'Effective yield', kind: 'credit', tier: 'C' },
      { instrument: 'ICE BofA BB', yieldPct: 6.05, asOf: '3 Sep 2026', basis: 'Effective yield', kind: 'credit', tier: 'C' },
      { instrument: 'ICE BofA BBB', yieldPct: 5.86, asOf: 'Sep 2026', basis: 'Effective yield', kind: 'credit', tier: 'C' },
      { instrument: 'US Treasury 10-year', yieldPct: 5.01, asOf: '16 Sep 2026', basis: 'Highest since mid-2007', kind: 'sovereign', tier: 'C' },
      { instrument: 'US Treasury 2-year', yieldPct: 4.74, asOf: '16 Sep 2026', basis: '', kind: 'sovereign', tier: 'C' },
      { instrument: 'Fed funds (upper bound)', yieldPct: 4.0, asOf: '16 Sep 2026', basis: 'Raised 25bp to 3.75–4.00%; CPI 3.4% (Aug)', kind: 'sovereign', tier: 'C' },
      { instrument: 'Peer dividend yields — BX 4.2 · BAM 4.4 · TPG 4.5 · CG 3.4', yieldPct: 4.2, asOf: 'Sep 2026', basis: 'Blackstone shown; the others in the peer table', kind: 'peer', tier: 'C' },
    ],
    rowsNote:
      'The ladder places the equity between the bond market and its own fund. Read top-down: the manager\'s 8.8% distributable-earnings yield sits above single-B corporate paper (7.3%) and below its own BDC (11.4% on price) and the loans that BDC holds (10.4% income). In January 2025, at the peak, the same DE yield was 3.1% against a 10-year Treasury near 4.6% — a negative equity-yield gap, which is what a permanence premium looks like at its most extreme. Today the gap is +3.8 points over the 10-year and +2.7 over BB. Note that the manager yields less than its fund: correctly so, since the manager\'s earnings grow and carry no credit loss, but the spread between the two has compressed from roughly five points in 2021 to under three — the market has moved the manager most of the way to being priced as a credit instrument.',
    buckets: [
      { bucket: 'Credit — perpetual wealth vehicles and BDCs', sharePct: 58.2, duration: 'Perpetual in form; 5% per quarter repurchase right in substance', liability: 'Puttable. Q2 requests: OCIC 18.8%, OTIC 38.1% of shares', requiredYieldPct: 9.0, build: '2-year Treasury 4.74 + a BB-type credit spread 1.3 + a redemption-cycle premium 3.0. The put is the investor\'s; the 2-year, not the 10-year, is the right anchor.' },
      { bucket: 'GP Strategic Capital — minority stakes in managers', sharePct: 25.0, duration: '10 years plus; no redemption mechanism', liability: 'None at the fund level; illiquid for the fund investor (see the Petershill note)', requiredYieldPct: 7.9, build: '10-year Treasury 5.01 + BBB spread 0.85 + 2.0 for illiquidity and single-manager risk.' },
      { bucket: 'Real Assets — net lease and digital infrastructure', sharePct: 16.8, duration: 'Long-dated, contractual', liability: 'Finite funds and perpetual vehicles; no gate reported', requiredYieldPct: 7.4, build: '10-year Treasury 5.01 + BBB spread 0.85 + 1.5 for illiquidity.' },
    ],
    dePs: 0.87,
    bucketNote:
      'Weighting the three required yields by each platform\'s share of management fees gives 8.5%. Capitalising LTM distributable earnings of $0.87 at 8.5% with no growth gives $10.29 a share — within 5% of the $10.85 probability-weighted value the scenarios produce by an entirely different route, and 4% above the price. Each percentage point of durable growth is worth roughly $1.50 a share at these yields. The exercise is tier D from top to bottom — every spread is a judgement — and its value is in the structure, not the point estimate: at 8.8% the market is pricing the whole fee stream at the required yield of its puttable part, giving no credit for the 42% that is genuinely long-dated. If the puttable book stabilises, that is the mispricing; if it does not, the market is right and the long-dated 42% is the residual value.',
    verdict:
      'Against bonds, Blue Owl is priced as what 2026 revealed it partly to be: a credit instrument with a put held by someone else. A 106%-payout dividend at 9.3% is not a coupon and should not be compared to one; the 8.8% distributable-earnings yield is the honest figure, and it sits three points over the 10-year Treasury, two and a half over BB, and three below the fund it manages. The bucket arithmetic says a bond investor who believed the permanence claim for the GP-stakes and real-asset fee streams — and only those — would already pay today\'s price for the company. The permanence claim on the other 58% is what the next two quarters of tender data will decide, and it is the one thing no yield comparison can settle.',
  },

  sources: [
    { label: 'Share price $9.88, 52-week range $7.95–$19.29, market capitalisation, dividend yield', publisher: 'Market data aggregators', period: '18 September 2026', tier: 'C' },
    { label: 'Total-return index (14 Dec 2020 = 100): 147 / 109 / 160 / 259 at each year-end 2021–2024', publisher: 'Blue Owl Capital FY2024 10-K, performance graph', period: 'FY2024', tier: 'A', url: 'https://www.sec.gov/Archives/edgar/data/1823945/000182394525000013/owl-20241231.htm' },
    { label: 'Annual total returns 2022–2025; year-end 2025 close $14.99; 52-week high $19.29 on 18 Sep 2025', publisher: 'Market data aggregators', period: '2022–2025', tier: 'C' },
    { label: 'All-time high $26.73 intraday (24 Jan 2025); record-low close $8.45 (6 Apr 2026); intraday low $7.95 (2 Apr 2026); −68% from peak', publisher: 'Bloomberg / Yahoo Finance / Seeking Alpha', period: 'Jan 2025 – Apr 2026', tier: 'C' },
      { label: 'Dividends declared by quarter: Q4 2021 $0.10; 2022 $0.10 / $0.11 / $0.12 / $0.13; 2023 fixed $0.14; $0.04 paid Jan–Sep 2021', publisher: 'Blue Owl Capital 8-K earnings releases / 424B2', period: '2021–2023', tier: 'A', url: 'https://www.sec.gov/Archives/edgar/data/1823945/000182394523000006/a123122-ex991xearningspres.htm' },
    { label: 'Q3 and Q4 2021 results — FRE $0.11 / $0.12, DE $0.11 / $0.12 per adjusted share; AUM $94.5bn', publisher: 'Blue Owl Capital', period: 'FY2021', tier: 'A', url: 'https://ir.blueowl.com/Investors/news/news-details/2022/Blue-Owl-Capital-Inc.-Reports-Fourth-Quarter-2021-Results/default.aspx' },
    { label: 'FY2023 FRE $0.70 / DE $0.65 per share as first reported (this memo carries $0.68 / $0.62, summed from the quarterly releases); FY2024 FRE $0.86 / DE $0.77 (+26% / +22%)', publisher: 'Blue Owl Q4 2023 and Q4 2024 earnings calls', period: 'FY2023–24', tier: 'A' },
    { label: 'Altimar / Owl Rock / Dyal — $45bn AUM, ~$12.5bn post-transaction value, $1.8bn proceeds, 91% permanent capital; S-4 projections (revenue, DE to common, 75% illustrative payout, 68–70% margin)', publisher: 'SEC Forms S-4 / 424B3 / DEFA14A, as surfaced', period: 'Dec 2020 – May 2021', tier: 'C', url: 'https://www.sec.gov/Archives/edgar/data/1823945/000119312521146881/d46228d424b3.htm' },
    { label: 'Series E-1 and E-2 earn-out triggering events, 21 Jul and 3 Nov 2021; 7,495,432 + 42,504,530 units', publisher: 'Blue Owl Capital 10-Q / 424B3', period: '2021', tier: 'A' },
    { label: 'Acquisitions — Oak Street $950m + $650m earn-out; Wellfleet ~$140m; Prima ~$170m; Kuvare $750m ($325m cash / $425m stock); Atalaya $450m (~$350m equity); IPI ~$1.0bn (80% equity)', publisher: 'Blue Owl press releases / 8-Ks via Connect CRE, MarketScreener, Pillsbury, FinTech Futures, Investing.com', period: '2021–2025', tier: 'A' },
    { label: 'Owl Rock founding (2016) and founders; Dyal formation (2011) and Neuberger Berman ownership', publisher: 'Blue Owl / SEC / Axios', period: '2011–2021', tier: 'C' },
    { label: 'Dyal II net IRR 24%; Dyal III net IRR 26%; Dyal IV $9.0bn, marketed IRR 34%; Fund III securitisation; Fund IV $1.5bn secondary', publisher: 'Buyouts Insider / Secondaries Investor / Private Equity Wire / New Jersey Division of Investment', period: '2015–2026', tier: 'C' },
    { label: 'ORCC 11.8% IRR on realised investments since inception', publisher: 'Owl Rock Capital Corporation proxy', period: '2020', tier: 'A' },
    { label: 'OBDC Q2 2026 — NAV $14.26 (from $14.41), adjusted NII $0.34, dividends $0.33, portfolio $15.0bn; price $11.08, yield 11.4%', publisher: 'Blue Owl Capital Corporation 8-K / 10-Q; aggregators', period: 'Jun–Sep 2026', tier: 'A' },
    { label: '19 Feb 2026 $1.4bn loan sale and end of OBDC II quarterly liquidity; 24 Feb Deutsche Bank downgrade; Q1 2026 redemption requests $5.4bn; 19 Nov 2025 merger termination', publisher: 'CNBC / Bloomberg / Fortune / Morningstar', period: 'Nov 2025 – Apr 2026', tier: 'C' },
    { label: 'Sell-side: average target $14.93 from $16.40; Barclays Hold (15 Sep); KBW to Market Perform; FY2027 EPS $1.30 (Zacks) vs $1.71 (consensus); golden cross reported 14 Aug', publisher: 'Simply Wall St / TipRanks / MarketBeat / Invezz', period: 'Aug–Sep 2026', tier: 'C' },
    { label: 'Peer results Q2 2026 — Ares, Apollo, Blackstone, KKR, Carlyle, TPG, Brookfield AM, GCM Grosvenor, Vinci Compass; Q1 FY2027 — Hamilton Lane, StepStone', publisher: 'Company releases via PR Newswire, GlobeNewswire, SEC 8-Ks, Investing.com', period: 'Jul–Aug 2026', tier: 'A' },
    { label: 'Peer prices and market capitalisations', publisher: 'Market data aggregators (Yahoo, CNN, Morningstar, Robinhood, StockAnalysis, MacroTrends)', period: '5–18 September 2026', tier: 'C' },
    { label: 'Petershill Partners delisting — $4.5bn valuation, $921m capital return, ~35% premium', publisher: 'Investing.com / Hedgeweek / The Middle Market / PEI', period: '2025–2026', tier: 'C' },
    { label: 'Credit share of fee-earning assets — APO 86%, ARES 66%, OWL 53%, KKR 48%', publisher: 'Morningstar', period: 'Mar 2026', tier: 'C' },
    { label: 'US Treasury 10-year 5.01%, 2-year 4.74% (16 Sep); Fed funds 3.75–4.00%; CPI 3.4% (Aug)', publisher: 'Trading Economics / ETF Trends / CNBC / BLS', period: 'September 2026', tier: 'C' },
    { label: 'ICE BofA effective yields — BBB 5.86%, BB 6.05%, B 7.27%, CCC 14.9%', publisher: 'FRED / Trading Economics', period: 'September 2026', tier: 'C' },
    { label: 'Cliffwater Direct Lending Index — 2025 return 9.3%, interest income 10.4%, PIK 0.7%; H1 2026 3.0%, trailing year 7.7%', publisher: 'Cliffwater via PR Newswire / Morningstar', period: '2025 – Jun 2026', tier: 'C' },
  ],
}
